### ISSUE TITLE
Ошибка интерфейса.

### ISSUE THREAD

**Issue by TheTitanrain** [pavel-pimenov/flylinkdc-r5xx#13]
При запуске флай говорит, что восстановлена папка, которая раньше была в шаре. При это в диалоге находятся две кнопки "Да" и "Нет".
Вопроса никакого нет, а да и нет есть.

**Comment by pavel-pimenov** [comment]
Спасибо. поправил
https://code.google.com/p/flylinkdc/source/detail?r=18408
код пока на гитхаб не перенесен - тут обновиться исходник чуть позже скоро
