### ISSUE TITLE
Хэширование файлов "спотыкается" о "файл", который является символической ссылкой на другой файл, и стоит на месте (никогда не заканчивается)

### ISSUE THREAD

**Issue by ilyakanevsky** [pavel-pimenov/flylinkdc-r5xx#14]
Win7 x64 SP1 Pro, NTFS
FlylinkDC++ r502-x64 build 18654

По пути "D:\Музыка\Транс\Lange\04. Other\Judge Jules - Weekend Warmup (Menno De Jong & Lange Guests) (24.02.2012).mp3" у меня лежит символическая ссылка на "D:\Музыка\Транс\Menno De Jong\Judge Jules - Weekend Warmup (Menno De Jong & Lange Guests) (24.02.2012).mp3".

Ссылка создана в FAR2 путем нажатия Alt-F6 и далее выбрано "Тип ссылки" = "символическая ссылка (файл)". В Проводнике Windows эта ссылка называется «Файл "SYMLINK"».

В окне Flylink'а "Хеширую файлы..." (вызывается по Ctrl-H) видно, что скорость по нулям, осталось еще 2000+ файлов, и вверху отображается "D:\Музыка\Транс\Lange\04. Other\Judge Jules - Weekend Warmup (Menno De Jong & Lange Guests) (24.02.2012).mp3". И дальше ничего не происходит. См. скриншот "Ctrl-H.png".

У файла, на который ссылается ссылка, стоял атрибут "Только чтение". Убрал. Не помогло.

И у файла, и у ссылки стоят атрибуты "Архивный" и "Неиндексируемый". (Последним атрибутом пользуюсь в своих хитрых целых — установка атрибута у меня означает "прослушанная музыка / просмотренный фильм", и соответствующая раскраска в FAR2 делается. На индексирование моих файлов методами Windows мне плевать, встроенным поиском все равно никогда не пользуюсь).

Могу выполнить любую дополнительную диагностику, только скажите, какую :-).
![ctrl-h](https://cloud.githubusercontent.com/assets/12554484/7763839/e0364aea-0068-11e5-85fe-b590f202212a.png)

**Comment by pavel-pimenov** [comment]
Скопируй FlylinkDC.exe в другой каталог - например C:\123
запусти и расшарь только каталог D:\Музыка\Транс\Menno De Jong\
он не будет вешаеться на этом файле?

**Comment by ilyakanevsky** [comment]
Попробовал, вся папка Menno De Jong успешно прохэшировалась. Потом добавил папку Lange — встало на том же месте, см. скриншот.
![2015-05-22 13_45_57-](https://cloud.githubusercontent.com/assets/12554484/7766242/06339246-0089-11e5-8072-edd7bc8303df.png)

**Comment by ilyakanevsky** [comment]
Причем, судя по Process Monitor, по ссылке он перешел, см. скриншот.
![2015-05-22 13_51_29-process monitor - sysinternals_ www sysinternals](https://cloud.githubusercontent.com/assets/12554484/7766325/f12c8c12-0089-11e5-9231-1c997aeff650.png)

**Comment by pavel-pimenov** [comment]
Спасибо за хороший баг-репорт.
проблему повторил - для такой ссылки функция FindFirstFileEx почему-то не возвращает размер файла и он считается = 0 
буду разбираться и обязательно поичиню.

**Comment by ilyakanevsky** [comment]
Супер. Если уже и название проблемной функции известно, то, надеюсь, дальнейшее разбирательство не займет много времени. Спасибо за быструю реакцию!

**Comment by pavel-pimenov** [comment]
Исправил
https://code.google.com/p/flylinkdc/source/detail?r=18657
вечером опубликую бетку проверьте что все ок и закройте issue 
Cпасибо за аларм :)

**Comment by ilyakanevsky** [comment]
Проверил, все ок, хэширование не спотыкается, и успешно доходит до конца.
Обнаружились еще забавные штуки, связанные с символической ссылкой, счас открою новый баг :-)
