### ISSUE TITLE
Разные неправильности при обработке символических ссылок на файлы (SYMLINK)

### ISSUE THREAD

**Issue by ilyakanevsky** [pavel-pimenov/flylinkdc-r5xx#15]
В качестве продолжения https://github.com/pavel-pimenov/flylinkdc-r5xx/issues/14: хэширование прошло успешно, смотрю в свой список файлов, чтобы проверить, насколько успешно обработался "файл"–символическая ссылка. Косяки:

1. Смотрим в ту папку, где лежит символическая ссылка, см. вложение "symlink_fail.png":
 - довольно странно, что путь указывает на текущую папку (подчеркнуто желтой линией), а не на папку, в которой реально располагается настоящий файл — сомнительный момент, может фэйл, может нет;
 - свойства реального файла не считались (выделено красной рамкой) — это явный фэйл.

2. Смотрим в ту папку, где лежит настоящий файл , см. вложение "real_file_path_fail.png":
 - путь указывает на папку, где лежит символическая ссылка на текущий настоящий файл! (а если бы ссылок было несколько?..), подчеркнуто красной линией — это явный фэйл;
 - свойства реального файла успешно считались (выделено зеленой рамкой) — это гуд.
![symlink_fail](https://cloud.githubusercontent.com/assets/12554484/7793828/092aa714-02e6-11e5-831f-994fd54d91d4.png)
![real_file_path_fail](https://cloud.githubusercontent.com/assets/12554484/7793833/0d2132ac-02e6-11e5-9380-ce0a9ec87d3e.png)

**Comment by pavel-pimenov** [comment]
На первом скрине - желтым это так и задумано - ведь открывается ссылка по этому пути.
а то что она смотри на другой файл - это не важно.
ты можешь рядом насоздавать много ссылку с разным именем на один и тот-же файл
а вот не посчиталась медиаинфа - это ошибка буду чинить.

Про второй скрин пока не осознал - нужно повторить у себя в отладке.

**Comment by pavel-pimenov** [comment]
Первую ошибку исправил. спаисбо. вечером будет новая бетка.

**Comment by pavel-pimenov** [comment]
Вторая ошибка тоже понятна.
В этой колонке выводит информация на основании поиска по TTH
columns[COLUMN_PATH] = Text::toT(Util::getFilePath(ShareManager::toRealPath(f->getTTH())));
т.к. у вас фактически 2 файла с одинаковым TTH то выводится путь который нашелся первым.
Как предлагаете это чинить?
Выводить список путей где встретился этот TTH?
а если таких TTH очень много...

**Comment by pavel-pimenov** [comment]
Стало быть все исправил? закрываю

**Comment by ilyakanevsky** [comment]
Ой-ой-ой. Что-то я забыл про эту тему.
> Как предлагаете это чинить?
Всегда при нахождении ссылки добираться до исходного файла / его исходного расположения, и хранить в базе именно настоящий файл/папку, а не ссылку. Тогда все описанные мной проблемы автоматически разрешатся.
