### ISSUE TITLE
В инет хабах перестаёт отображаться флаг страны

### ISSUE THREAD

**Issue by Krulk** [pavel-pimenov/flylinkdc-r5xx#1611]
При первом открытии списка инет хабов он выглядит так:
http://i68.fastpic.ru/big/2015/0908/85/a4769e32a2137f58fc902a303f5d2b85.png
При повторном открытии списка инет хабов он выглядит так:
http://i65.fastpic.ru/big/2015/0908/8d/5ab443866b6b86868b0f9db28c41938d.png
Слева от названия хаба перестаёт отображаться флаг страны.

**Comment by pavel-pimenov** [comment]
Спасибо. повторилось.

**Comment by pavel-pimenov** [comment]
В след будет будет все ок.
