### ISSUE TITLE
Не обновляется ip при нажатии на "Тест портов и определение ip"

### ISSUE THREAD

**Issue by Krulk** [pavel-pimenov/flylinkdc-r5xx#1612]
В режиме "Браундмауэр с ручным перенаправлением", когда щёлкаешь на "Тест портов и определение ip" IP адрес не обновляется на текущий внешний (порты нормально проверяются). У меня динамический внешний адрес L2TP и при переподключении инета выдаётся новый ip, FL его обновляет по таймеру и при перезапуске, но иногда быстрее просто нажать "Тест портов и определение ip".
Раньше эта опция работала и была отключена из-за юзеров у которых 1 локальный хаб. Им лень  прописывать ip к этому хабу в настройках хаба или отключать автообновление ip по времени.
Предлагаю вернуть всё как было, но для всех режимов подключения сделать небольшую кнопку "Заблокировать" возле поля ip при нажатии которой даже если включено автообновление по времени и после перезапуска, ip всё равно останется тот что был введён вручную.

**Comment by pavel-pimenov** [comment]
А почему ты сидишь на ручном режиме а не на upnp?

**Comment by Krulk** [comment]
Потому что всегда сидел в ручном режиме, кроме того на новой прошивке роутера upnp без проблем сам настраивается на работу с инетом, но локалка не работает, приходится в ручном режиме прокидывать 2 порта на инет и 2 порта на локалку и тогда всё работает (на старой прошивке отдельно на локалку ничего прокидывать было не надо, но всё равно upnp не пользовался).
