### ISSUE TITLE
Падение клиента

### ISSUE THREAD

**Issue by pozitivv** [pavel-pimenov/flylinkdc-r5xx#1613]
за последние сутки клиент r503-x64 build 19122 упал три раза, до этог подобного небыло.

**Comment by pavel-pimenov** [comment]
11.10.2015 17:46, pozitivv пишет:

а можно прислать адреса на дамп падения - там после падения сайт ведь 
открывался?
вот мне нужно эти три адреса.

> за последние сутки клиент r503-x64 build 19122 упал три раза, до этог 
> подобного небыло.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/pavel-pimenov/flylinkdc-r5xx/issues/1613>.
>


-- 
~PPA() {} //
http://flylinkdc.blogspot.com/ - актуальные версии FlylinkDC++ и StrongDC++ sqlite

**Comment by pozitivv** [comment]
а где их взять?

**Comment by pavel-pimenov** [comment]
11.10.2015 17:58, pozitivv пишет:
>
> а где их взять?
>
>
в истории браузера?
нажмите в нем Ctrl+H и поищите https://drdump.com

**Comment by pozitivv** [comment]
блин я закрыл и заново запустил, если ещё упадет напишу. думал может в логах чего останется

**Comment by pavel-pimenov** [comment]
Браузер ведь помнит историю?

**Comment by pozitivv** [comment]
я на сайт не заходил
