### ISSUE TITLE
Замерзание клиента при обновлении

### ISSUE THREAD

**Issue by mikekmv** [pavel-pimenov/flylinkdc-r5xx#1614]
Проявляются тормоза клиента при пуске и замерзание при обновлении,
возможно это не связанные явления, но сейчас разобраться непросто.

https://yadi.sk/i/LQ0_qmJ8jmNQU - скрин
https://yadi.sk/d/a4xbDIPjjmNu9 - логи
https://yadi.sk/d/3cX7NWMLjmNNQ - дамп
Предыдущие версии:
https://yadi.sk/i/sl0hcl_rjQCwu
https://yadi.sk/i/FF-BgWT-icD6S
https://yadi.sk/i/53PffzKticD73

**Comment by pavel-pimenov** [comment]
Спасибо - нашел причину.
у тебя много файлов в шаре - а я добавил передачу числа файлов на хаб.
весит на секции. поправлю сегодня.

**Comment by pavel-pimenov** [comment]
Обновил программу.
Подмерзания по дампам должны пропасть - проверь.
и если все ок - опиши.
