### ISSUE TITLE
Долгий старт: Так ли необходимо обновление списка файлов при старте флая?

### ISSUE THREAD

**Issue by Chrizt** [pavel-pimenov/flylinkdc-r5xx#1617]
Сейчас, при старте флая, происходит принудительное обновление списка файлов, при этом, конечно же, видно только сплэш. Приходится долго ждать, пока флай целиком запустится, хотя когда клиент работает, и в фоне обновляется список файлов - он хоть не так сильно вешает всё: интерфейс наглухо может подвиснуть, но закачки и фоновые процессы идут (поиск альтернатив, прозвон портов, обновление DTH, обновление IP, ну и т.д.)
Во всяком случае, мне так кажется - что при доступном интерфейсе фоновый процесс лучше, чем когда сплэш висит :8ball:

**Comment by pavel-pimenov** [comment]
А как определили что основное время занимает обновление файл-листа?

**Comment by Chrizt** [comment]
Смотрел System.log
16 Окт 2015 г. 17:10 пользователь Pavel Pimenov <notifications@github.com> написал:А как определили что основное время занимает обновление файл-листа?

**Comment by Chrizt** [comment]
Пардон за цитатку

**Comment by pavel-pimenov** [comment]
А кинь кусок этого лога?

**Comment by Chrizt** [comment]
У компа буду не раньше понедельника - тогда непременно скину.

**Comment by Chrizt** [comment]
А, нет, пардон, я перепутал. Это так долго грузится моя очередь:

[2015-10-19 09:29:10] [Step] [StartUp] Begin load Очередь скачивания [1 ms]
[2015-10-19 09:29:10] Обновление списка файлов запущено
[2015-10-19 10:14:45] [Step] [StartUp] End load Очередь скачивания [2735564 ms and 2739411 ms after start]
[2015-10-19 10:14:45] [Stop] [StartUp] [110 ms, Total: 2739521 ms]

**Comment by pavel-pimenov** [comment]
Сколько записей в очереди?
можешь закрыть флай - пожать все файлы Fly*.sqlite
расшарить архив в облаках и кинуть мне  на pavel.pimenov@gmail.com

**Comment by Chrizt** [comment]
Пока по почте пообщаемся на эту тему, не против?

**Comment by pavel-pimenov** [comment]
да. ок. закрываю тогда тикет тут
