### ISSUE TITLE
В Настройках соединения недоступны некоторые пункты

### ISSUE THREAD

**Issue by Krulk** [pavel-pimenov/flylinkdc-r5xx#1623]
В настройках соединения галки:
Не учитывать настройки хабов/UPnP
Work in passive mode if specified active mode not available (autodetect)
не доступны (серые) ни в одном из режимов соединения.

**Comment by pavel-pimenov** [comment]
Расскажи что ты ожидаешь от этой галки? знаешь как она должна работать?

**Comment by Krulk** [comment]
Птока работает по-своему правильно, сама определяет реальный ip с которого я к ней присоединяюсь (192.168.1.1 если зашёл через инет ip хаба,и роутер завернул меня через себя, или 192.168.1.2 если захожу сразу на 192.168.1.10 (локальный адрес хаба)), отправляет этот ip инет юзеру с которого хочу скачать, юзер видит 192.168.1.1 и ответы от него не доходят (возможно всё ещё проще, т.к. у инет юзера даже не отображается что я к нему пытаюсь присоединиться).

Хочу от птоки, чтобы она принимала указанный в настройках клиента ип и порты, сообщала о попытке скачать инет юзеру с этого ипа и порта. Но она упорно определяет мой реальный локальный ип, а инетовский ip роутера указанные в настройках клиента игнорирует при любых настройках хаба и клиента.

Зачем тогда в клиенте есть возможность задавать ип вручную если птока его напрочь игнорирует. Есть хаб в локалке провайдера, в FL в настройках этого хаба я задаю ip  роутера в локалке провайдера 10.62.73.221, прокидываю порты для FL в локалку провайдера и только тогда могу скачивать с хаба (это работает и это правильно). Почему тоже самое не работает для хаба в домашней сетке непонятно.

На форумах говорят что в ранних версиях птоки была галка при снятии которой ипы указанные в натройках клиента не игнорировались, но это давало возможность ддосить юзеров, поэтому эту фишку убрали. Для профиля опа пробовал ставить галку "Игнорировать проверку IP для профиля", качать не начало.


Не исключаю что проблема просто в маршрутизации или конкретно моём роутере (Keenetic Giga, прошивка 2 серии).


>Понедельник,  2 ноября 2015, 23:58 -08:00 от Pavel Pimenov <notifications@github.com>:
>
>Расскажи что ты ожидаешь от этой галки? знаешь как она должна работать?
>—
>Reply to this email directly or  view it on GitHub .




**Comment by Krulk** [comment]
ой ой, верхний комент, это к другому моему исулес )))) Я перепутал слова галка и птока )))) а про галки:
Не учитывать настройки хабов/UPnP - индивидуальные настройки в избранных хабах игнорируются, используются общие для всех в файл-настройка
Work in passive mode if specified active mode not available (autodetect) - жду, что FL будет переключаться в пассив если актив недоступен (может даже если не удаётся скачать в активе пару минут, переходить в пассив для данной закачки).
