### ISSUE TITLE
Пропадание окон и "серый фон".

### ISSUE THREAD

**Issue by mcdemon05** [pavel-pimenov/flylinkdc-r5xx#1627]
По непонятным причинам, во флайлинке иногда куда-то сворачиваются окна.
В результате вместо окон хабов, виден просто серый фон.
Что-бы это исправить, приходится открывать служебное окно (например поиск) и разворачивать его.
Баг я запечатлел на видео, которое прикрепляю к данному сообщению в виде ссылки на архив RAR5 (нужен winrar не ниже 5 версии).
https://yadi.sk/mail/?hash=2qFLxOWyG%2BRnDvqM6kWlIpFssRnghS9QwJcWIqQ4J%2BE%3D

**Comment by pavel-pimenov** [comment]
Пришли мне на почту DCPlusPlus.xml Favorites.xml

**Comment by pavel-pimenov** [comment]
Исправлено.
Спасибо. проблема была в том что в Favorites.xml 
в атрибутах WindowPosX="-768" WindowPosY="-789" как-то оказались отрицательные значения.
