### ISSUE TITLE
После гибернации и при перезапуске не подтягивается netbios шара

### ISSUE THREAD

**Issue by melnikaite** [pavel-pimenov/flylinkdc-r5xx#1628]
Win 10 x64 r502
Расшариваю по netbios или с сетевого диска, но после запуска приложения или после гибернации пишет, что моя шара 0 байт
Помогает только кнопка обновления собственного списка файлов или перерасшаривание из настроек

**Comment by pavel-pimenov** [comment]
Обновитесь до последней версии?
Меню-помощь-проверить обновления.

**Comment by melnikaite** [comment]
Пишет что установленная версия является последней
build 16901

**Comment by pavel-pimenov** [comment]
Можете показать что пишет в статусной строке?
по какому адресу она проверят новую версию?

**Comment by pavel-pimenov** [comment]
Вот такой скрин сделайте https://yadi.sk/i/qUM1DDpQmEoTm

**Comment by melnikaite** [comment]
![r502](https://cloud.githubusercontent.com/assets/900724/11808725/53935132-a333-11e5-9118-a2ced4e620f0.png)

**Comment by pavel-pimenov** [comment]
Хм. так у вас не флайлинк а сборка на ее основе - которую делал Слава для атлант телекома.
она обновления ищет на их сервере.
тут я не могу помочь.

как вариант можете попробовать рядом поставить флайлнк оригинальный
http://www.fly-server.ru/install/r5xx/release/

и подсунуть ему 
DCPlusPlus.xml
Favorites.xml

от вашей сборки
во флае с 0 шарой должно быть все уже хорошо.
попробуете так?

**Comment by melnikaite** [comment]
попробовал, спасибо, обновление помогло
