### ISSUE TITLE
Свойства отдач/закачек копируются по 2 раза.

### ISSUE THREAD

**Issue by Krulk** [pavel-pimenov/flylinkdc-r5xx#1629]
1. При копировании свойств отдачи/закачки в панели отдач/закачек внизу, все данные копируются 2 раза в виде строк: 7.48 МБ/с7.48 МБ/с ; 109.252.23.177109.252.23.177 и т.д.

2. Меню Копировать которое относится не к списку пользователей а конкретному пользователю из этого списка в панели отдач/закачек, не работает. Также в нём присутствует лишнее слово Копировать. Пример Копировать -> **Копировать** Ник

**Comment by pavel-pimenov** [comment]
Исправил. для 2-го нужно обновление локализации - будет позже
