### ISSUE TITLE
Окно Manual P2P Guard заблокированно для редактирования

### ISSUE THREAD

**Issue by Krulk** [pavel-pimenov/flylinkdc-r5xx#1631]
- Окно Manual P2P Guard заблокировано для редактирования и невозможно вручную исключить добавленные туда IP.
- В меню по правой кнопке на Edit, Memo и других строках ввода присутствуют пункты связанные с Юникодоом, они там точно нужны?
http://storage3.static.itmages.ru/i/16/0512/h_1463088838_1282731_e8b81acc13.png

**Comment by pavel-pimenov** [comment]
Исправлено - ожидайте в след бетке.
