### ISSUE TITLE
Отключение IPTrust.ini

### ISSUE THREAD

**Issue by Krulk** [pavel-pimenov/flylinkdc-r5xx#1632]
Необходимо добавить галочку Включить IPTrust с блокировкой окна IPTrust от редактирования, чтобы у пользователей не возникало вопросов почему вдруг появляются надписи заблокировано IPTrust.ini. Это нужно для того, чтобы  пользователь не заблокировал скачку/отдачу случайно добавив в IPTrust.ini хотя бы 1 цифру. Встречал большое количество юзеров с жалобами на IPTrust.

Ещё вопрос, почему при добавлении любого ип адреса или любой цифры в IPTrust.ini скачка/отдача абсолютно со всех остальных адресов блокируется? Не лучше ли сделать блокировку скачки со всех адресов исключительно вручную, а уже потом добавлять разрешение на скачку/отдачу.

Например задача: разрешить качать/отдавать адресам: 192.168.14.6, 192.168.0.1-192.168.0.255, остальным запретить:
Содержимое  IPTrust.ini сейчас:
192.168.14.6
192.168.0.1-192.168.0.255
Содержимое при моём способе:
-0.0.0.0/0 (или -0.0.0.0-255.255.255.255)
192.168.14.6
192.168.0.1-192.168.0.255

Это даже при включенном IPTrust позволит избежать случаев блокировки скачки/отдачи при добавлении любого ИП или случайной цифры в IPTrust.ini. Сейчас при добавлении случайной цифры в IPTrust скачка/отдача всем ип блокируется наглухо.

**Comment by pavel-pimenov** [comment]
Добавил галку отключения IPtrust.ini - ожидайте в след бетке
