### ISSUE TITLE
Скачанный файл иногда остаётся занят процессом FL

### ISSUE THREAD

**Issue by Krulk** [pavel-pimenov/flylinkdc-r5xx#1634]
Иногда скачанный файл остаётся занят процессом FL и его возможно удалить только после закрытия FL. Это сильно мешает когда качается много больших файлов, а места на винте мало, FL не хочется закрывать, но приходится, чтобы разблокировать файл. Это происходит очень-очень редко и понять FL занял файл или нет, получается только после закрытия FL.

**Comment by pavel-pimenov** [comment]
Исправлено.
