### ISSUE TITLE
Подсветить файл в поиске, если он уже есть в очереди скачек

### ISSUE THREAD

**Issue by Krulk** [pavel-pimenov/flylinkdc-r5xx#1635]
Если файл уже находится в очереди скачек, хорошо подсветить его отдельным цветом в поиске, чтобы по 2 раза не кликать на нём и не качать то, что уже качается. Проверил, такая функция есть у всех клиентов Apex, GL, Strong и только FL никак не подсвечивает в поиске файл, который уже качается. FL подсвечивает только то что уже было скачано.
Цвет для подсветки качающегося файла лучше сделать настраиваемым. В других клиентах он не настраивается.

**Comment by pavel-pimenov** [comment]
Тут речь идет об окне поиска? или списка файл-листа?

**Comment by pavel-pimenov** [comment]
В следующей бетке будет светится в обоих окнах - проверьте и отпишите если что-то не так.
![default](https://cloud.githubusercontent.com/assets/920705/21451146/d44ba88c-c90d-11e6-87ef-eb1771ea9815.png)
