### ISSUE TITLE
Порядок колонок в панелях

### ISSUE THREAD

**Issue by Krulk** [pavel-pimenov/flylinkdc-r5xx#1636]
Возможно порядок колонок дело вкуса, но по-моему представленный ниже порядок основных  колонок в панелях и окнах оптимален:
Панель скачки внизу:
Пользователь | Имя файла | Размер | Скорость | Статус | Осталось | Путь | Хаб/Сегменты
Окно поиска:
Файл | Совпадения | Пользователь | Тип | Размер | Точный размер | Путь | Хаб

В одном из недавних обновлений в панели скачки колонку Статус зачем-то переместили на 2 место после колонки Пользователь, не изменив порядок следования колонок в меню правой кнопки. Вручную вернул колонку обратно.

**Comment by pavel-pimenov** [comment]
Положение колонок сохраняется - правда там есть баг и иногда колонки слетают (при обновлении)
это в процессе починки
