### ISSUE TITLE
Много записей в логе: Skip duplicate Update queue_item id

### ISSUE THREAD

**Issue by Krulk** [pavel-pimenov/flylinkdc-r5xx#1638]
В логе скапливается большое количество записей со ссылкой на разные файлы в очереди скачки:
началось/продолжается:
[2015-10-28 20:48:35] [!]Skip Duplicate update queue_item id = 3 Target = Путь\Файл
[2016-05-21 12:45:14] [!] Skip duplicate Update queue_item id = 10332 Target = Путь\Файл
Получается в логе уже 10332 таких записи, каждая из которых повторяется по 1-100 раз. Это нормально?

**Comment by pavel-pimenov** [comment]
Исправлено. проверьте и закройте проблему?

**Comment by Krulk** [comment]
за последние 3 дня таких записей не появлялось, закрываю.
