### ISSUE TITLE
Скачивание

### ISSUE THREAD

**Issue by LeshaRB** [pavel-pimenov/flylinkdc-r5xx#1645]
Заметил одну вещь

Добавляю файл в список для скачивания, закачка идет
Далее выхожу из флая и все закачка не идет, висит "Соединение устанавливается"

Приходится удалять этот файл и добавлять его заново, тогда опять качает

**Comment by pavel-pimenov** [comment]
Включите логирование в настройках и покажите что пишет в system.log ?

**Comment by LeshaRB** [comment]
Где его включить, чтоб долго не лазить

**Comment by pavel-pimenov** [comment]
https://yadi.sk/i/E5l1ehTStenB8

**Comment by LeshaRB** [comment]
Вот качаю файл, качает немного
Перезагружаю, висит соединение...

https://mega.nz/#!idA1CZ5B!-gyvXy80Q8PV86WSJiRHSQzxbNmQKOnhJ5-z_0Xmljo

**Comment by SCALOlaz** [comment]
Через несколько минут закачка должна возобновиться. Наверное сразу после автоматического поиска альтернатив. ( меню в Настройках / Скачивание / Очередь )

**Comment by pavel-pimenov** [comment]
Закройте флай.
Загрузите версию от 22 июня http://www.fly-server.ru/install/r5xx/src-bin/r503/FlylinkDC-r503-x64-build-19766-2016.06.22-12.07.42.7z
и руками обновите исполняемый файл FlylinkDC_x64.exe
запустите и откажитесь от обновления - эта версия начнет качать?

**Comment by LeshaRB** [comment]
Да с этим качает, нормально все.

**Comment by LeshaRB** [comment]
Да с этим качает все,

**Comment by pavel-pimenov** [comment]
А можете вот эту тогда проверить еще
http://www.fly-server.ru/install/r5xx/src-bin/r504/FlylinkDC-r504-x64-vc2013-beta-build-19854-2016.07.28-09.16.53.7z

эта сборка на последних исходниках, но с другим более старым компилятором в VC++ 2013

**Comment by LeshaRB** [comment]
Тоже работает,

Но сначала стоит, я меняю приоритет на максимум, и сразу идет загрузка, 
Если не менять стоит просто

Это для двух версий, что дали, могу чуть позже посмотреть если не менять приоритет

**Comment by LeshaRB** [comment]
http://www.fly-server.ru/install/r5xx/src-bin/r504/FlylinkDC-r504-x64-vc2013-beta-build-19854-2016.07.28-09.16.53.7z

Запустил без переключения приоритета - висит, при изменении приоритета тоже висит
Скачивание начинается если выбрать самый высокий приоритет, тогда сразу идет загрузка

**Comment by pavel-pimenov** [comment]
Спасибо. про приоритет посмотрю. оставайтесь на связи. у меня на 2-х системах к сожалению такая проблема не воспроизводится :-(

**Comment by pavel-pimenov** [comment]
А до выставления приоритета на максимум какой стоит? Низкий (Авто) ?

**Comment by Krulk** [comment]
У меня всё нормально качает после перезагрузки FL. Другое дело, есть некоторые юзеры с которых или совсем не качает или 0-1кб/с, ну это или канал такой или они сами ограничивают.

**Comment by LeshaRB** [comment]
Стандартный - норма

**Comment by LeshaRB** [comment]
Могу видео записать, если кто не верит

**Comment by LeshaRB** [comment]
Опять эта ошибка скачивание начинается
Если по файл удалить и скачать заново
Или установить приоритет "Самый высокий" на другие не реагирует

r503-x64 build 20110

**Comment by pavel-pimenov** [comment]
Автоообновитесь - проблема должна уйти.
