### ISSUE TITLE
Утечка памяти r503-x64 build 19663

### ISSUE THREAD

**Issue by Kink-f** [pavel-pimenov/flylinkdc-r5xx#1646]
Добрый день!
В r503-x64 build 19663 наблюдается утечка памяти до такого состояния
![default](https://cloud.githubusercontent.com/assets/20712312/17230042/fd60a2b8-5522-11e6-985d-2af4daad65c6.png)
При закрытии флайлинк MappedFile уменьшается до 170Мб.
Если обновить версию до 19841, то не скачивает никаких файлов. Либо говорит что нет слотов, либо бесконечное ожидание соединения. Как-то проскакивало что я в пассивном режиме и не могу соединяться с другими такими же, хотя в настройках работающее UPnP (проверял не только порты в окне настроек, но и смотрел на роутере - проборсились).

Win7 x64

**Comment by pavel-pimenov** [comment]
Спасибо. - у старой версии утечку поправить сложнее.
Давайте попробуем заставить работать свежую.
Про скачку рядом обсуждается проблема:
https://github.com/pavel-pimenov/flylinkdc-r5xx/issues/1645
у вас тоже изменение приоритета помогает?

**Comment by pavel-pimenov** [comment]
Автообновите клиента - я откатился на VC++2013 давайте на нем посмотрим что с утечкой памяти.?

**Comment by Kink-f** [comment]
Спасибо, проверю только вечером. Также отпишусь по вопросам скачивания на обновлённом клиенте.

**Comment by Kink-f** [comment]
В новой версии размер MappedFile держится на уровне 300мб, закачки у меня заработали.
Спасибо!
