### ISSUE TITLE
Подвисание статуса удалённых скачек в панели скачек

### ISSUE THREAD

**Issue by Krulk** [pavel-pimenov/flylinkdc-r5xx#1648]
Если добавить файл в очередь скачивания, у юзера все слоты заняты, в панели скачек напишет:
[T][C] Скачано 0 Б (0.0%) за 0:00:37 [Отключен]
дальше удаляем файл из очереди скачивания, а эта надпись всё равно висит в панели скачек часами и не удаляется по Del.

upd. Не обязательно, чтобы у юзера были заняты слоты, статус скачек после удаления подвисает в любом случае.

**Comment by pavel-pimenov** [comment]
Какой номер билда или скрин?

**Comment by Krulk** [comment]
Вот скрин: http://storage6.static.itmages.ru/i/16/0816/h_1471353409_4118519_462ad53364.png
файл удалил из очереди, а его статус висит уже полдня.

**Comment by pavel-pimenov** [comment]
Спасибо - вечером гляну под отладчиком и буду чинить.
оставайтесь на связи.

**Comment by Krulk** [comment]
Исправилось! В v19892 статус удалённых закачек больше не остаётся в панели скачек!

Ещё заметил, что статус завершённых закачек (особенно список файлов, после того как его закроешь), продолжает висеть в окне скачек в виде:
Соединение...
Скачивание завершено, ожидание...
Соединение закрыто [Соединение закрыто]
Отключен [Отключен]

Эти статусы меняются последовательно сверху вниз и самые нижние статусы так и остаются висеть в панели.
Пример что остаётся висеть после скачки списков файлов: http://storage3.static.itmages.ru/i/16/0817/h_1471434033_4974544_89a768e167.png

**Comment by pavel-pimenov** [comment]
Но они ведь пропадают через некоторое время?

**Comment by Krulk** [comment]
Жду минут 10 пока не пропадают. Подожду ещё.

**Comment by pavel-pimenov** [comment]
10 минут уже много - значит где-то сломал еще. оставайтесь на связи

**Comment by Krulk** [comment]
Совсем не пропадают, жду уже часа два )
http://storage2.static.itmages.ru/i/16/0817/h_1471437014_9569817_040d92a046.png

**Comment by pavel-pimenov** [comment]
Обновите бетку

**Comment by Krulk** [comment]
Да, статус файлистов теперь не подвисает, всё отлично.

Ещё уже давно заметил, что иногда при постановке файла на закачку он не отображаются внизу в окне скачек, особенно если скорость большая а размер файла маленький и юзеров для скачки мало (1-2), статус закачке даже и не думает появляться. Пример на файле большого размера: http://storage9.static.itmages.ru/i/16/0817/h_1471439764_6881608_981258ec61.png
уже чуть ли не половина файла скачалась а статуса всё нет. После перезапуска FL статус для таких файлов появляется нормально.
Сейчас это особенно заметно, раньше мельтешение не закрыващихся  статусов файллистов  мешало.

**Comment by pavel-pimenov** [comment]
Ок. спасибо.

**Comment by pavel-pimenov** [comment]
Проверьте вот эту сборку https://yadi.sk/d/cneHp5YZuJSf3 тут будет пропадать прогресс?

**Comment by Krulk** [comment]
Проверил:
- При удалении скачки остаются зависшие сменяющееся сообщение: 
Соединение [Отключен] -> Соединение [Тайм аут соединения]
Соединение... -> Соединение [Тайм аут соединения]
http://storage3.static.itmages.ru/i/16/0818/h_1471512379_2609013_6200b8425c.png
- прогресс добавленных в скачку файлов сразу нормально отображается. Не удалось пока сделать, добавить файл в скачку а прогресса нет.

- выявил новый глюк, возможно связанный с другим Issules: открыл файллист юзера, начал качать с него 1 файл (файл редкий, 1юз в очереди), удалил этот файл из очереди скачки, дальше опять у этого юзера нажимаю скачать файл (толи этот, толи другой) файл добавляется в очередь и долго ничего не качает (вроде даже никакого статуса нет или Соединение....), изменяю приоритет на Пауза потом на Авто и всё скачка пошла. Не хочет сразу подхватывать скачку файла с юзера с которого в процессе скачки удалил файл.

**Comment by pavel-pimenov** [comment]
Пока откатил изменения - авто обновитесь.
пытаюсь повторить проблему у себя на тесте.

**Comment by Krulk** [comment]
В последней версии 19898 я перестал регистрировать все ошибки написанные сверху. Куда-то они все делись, все файлы начинают качаться сразу, зависаний статусов нету, всё ок. Наверно и искать ничего не надо.

**Comment by Krulk** [comment]
v19904 опять проявилась неисправность, файл качается а внизу статус его скачки не отображается:
http://storage4.static.itmages.ru/i/16/0825/h_1472140852_4158936_a6b6830dba.png
файлы были в шаре но онлайн юзеров не было, сделал поиск, юзер добавился, скачка началась, но в статусе ни 1 скачивающийся файл не отображается.

(на другие статусы не обращайте внимания, юзер ded_alexis видимо ограничил скорость 10б/с и когда он онлайн постоянно висит в очереди скачки с падающей скоростью 100кб/с-10б/с.)

**Comment by pavel-pimenov** [comment]
Проверьте в последних билдах - повторяется подвисание? поправил еще один момент

**Comment by Krulk** [comment]
r504-beta-x64 build 20253 подвисаний пока нет. Появился другой момент, FL не начинает качать  файлы после перезапуска (кроме 1), ждал пол часа, пишет Ожидание (пользователь в сети). Если произвести поиск этого файла, то FL тут же начинает его скачивать. http://savepic.net/8781309.png -  если сделать поиск нижнего файла он сразу начнёт качаться, хотя после перезапуска в течении получаса не качался.
Ещё не хватает команды Принудительная попытка в меню файлов в окне Очередь скачивания.

В GL была какая-то спец настройка повышающая шансы схватить слот (но конечно не в этом дело, но всё же)
<String Name="SettingsFakeAskslotTimeout">Уменьшить время ожидания слота (+50% к шансу схватить слот)</String>

**Comment by pavel-pimenov** [comment]
Да подвисание качалки есть - лечится еще сменой приоритета.
пока не нашел где сломалось  - закрою тогда эту проблему.

**Comment by pavel-pimenov** [comment]
Создам рядом про старт закачек после старта
