### ISSUE TITLE
Подвисание интерфейса при попытке просмотра медиаинформации

### ISSUE THREAD

**Issue by code-kot** [pavel-pimenov/flylinkdc-r5xx#1651]
r504-beta-x64 build 20106
Win7 x64

В результатах поиска в контекстном меню видеофайла выбираем "Просмотреть медиаинформацию". Окно флая зависает примерно на минуту (ни на что не реагирует, в конце заголовка основного окна добавляется "(не отвечает)"), потом вываливается диалог с информацией и все отвисает. Раньше этот диалог появлялся быстро.

Заметил такой эффект несколько обновлений назад.

**Comment by code-kot** [comment]
На r504-beta-x64 build 20140 уже не воспроизводится.

**Comment by adem4ik** [comment]
Не воспроизводится в r504-beta-x64 build 20140.

**Comment by pavel-pimenov** [comment]
Это возникает когда сервер не доступен - у меня для этого используется простая VPS :-)
