### ISSUE TITLE
Имя пользователя с которого качал файл преобразуется в какой-то код, это не удобно.

### ISSUE THREAD

**Issue by Krulk** [pavel-pimenov/flylinkdc-r5xx#1653]
Имя пользователя с которого качал файл, если пользователя долго нет, преобразуется в колонке Пользователи в какой-то код и невозможно понять что это за пользователь. Удобно, чтобы имя всегда отображалось правильно, а код пусть хранится в другом месте.
http://savepic.net/8694297.png

**Comment by pavel-pimenov** [comment]
Спасибо. исправлено - ожидайте в след обновлении
также добавлено и имя хаба где был юзер
![default](https://cloud.githubusercontent.com/assets/920705/21448880/6c9130aa-c8f8-11e6-8e85-ee369179ffd0.png)
