### ISSUE TITLE
Не начинает качать файлы после перезапуска 

### ISSUE THREAD

**Issue by pavel-pimenov** [pavel-pimenov/flylinkdc-r5xx#1654]
FL не начинает качать файлы после перезапуска (кроме 1), ждал пол часа, пишет Ожидание (пользователь в сети). Если произвести поиск этого файла, то FL тут же начинает его скачивать. http://savepic.net/8781309.png - если сделать поиск нижнего файла он сразу начнёт качаться, хотя после перезапуска в течении получаса не качался.
Ещё не хватает команды Принудительная попытка в меню файлов в окне Очередь скачивания.

В GL была какая-то спец настройка повышающая шансы схватить слот (но конечно не в этом дело, но всё же)
Уменьшить время ожидания слота (+50% к шансу схватить слот)

**Comment by Krulk** [comment]
Выяснил что FL не начинает качать файлы после переподключения к хабу.
Чтобы FL начал качать файл нужно
- сделать поиск этого файла
- обновить список пользователей на этом хабе
- скачать список файлов у пользователя

Что происходит в CMD:
- по завершению скачивания блока посылаются такие команды: http://savepic.net/8763385.png
- когда хаб с юзером отключился, по завершению блока,  посылается верхняя команда, ответа нет.
- когда хаб опять подключился, часто посылаются такие команды: http://savepic.net/8736761.png при этом подключения к юзеру на хабе не происходит.
- если сделать поиск файла или обновить список юзеров на хабе, то посылаются такие команды: http://savepic.net/8778747.png

**Comment by Krulk** [comment]
Ошибка пока не исправлена :(

**Comment by pavel-pimenov** [comment]
Автообновитесь - должно стать все ок
