### ISSUE TITLE
settings window size issue on hi

### ISSUE THREAD

**Issue by unauthorized-401** [pavel-pimenov/flylinkdc-r5xx#1656]
![image](https://cloud.githubusercontent.com/assets/1651240/21480538/82948e0e-cb66-11e6-8676-62d33f45bde8.png)

The window cannot be resized and is cropped.

**Comment by pavel-pimenov** [comment]
hm... windows? version?

**Comment by hi-q** [comment]
10 Pro, x64, 1607, build 14393.576, that's a custom win theme but the same thing happens with a default theme.

**Comment by pavel-pimenov** [comment]
WTL 10 - bug fixed
