### ISSUE TITLE
Юзер висит в панеле передач и как будто постоянно хочет что-то скачать

### ISSUE THREAD

**Issue by Krulk** [pavel-pimenov/flylinkdc-r5xx#1657]
Юзер -[RO][UWS][CTA] постоянно пытается подключиться, что-то скачать и весь день висит в окне передач снизу. CMD отладчик выдаёт это: http://savepic.net/8771798.png
Что ему нужно?

User info:
	Ник: -[RO][UWS][CTA]
	Location: Romania
	Nicks: -[RO][UWS][CTA]
	Хабы: dchub://warriors.freeway-fun.net:434
	Шара: 72.34 ГБ (77 674 012 963 Б)
	Описание: 
	Приложение: ApexDC++ 1.6.0
	Соединение: 11.92 МБ/с
	E-Mail: 
	Client Type: 0
	Mode: P
	Слоты: 3
	IP: 5.14.199.84 (5-14-199-84.residential.rdsnet.ro - Romania)
	Known supports: MiniSlots XmlBZList ADCGet ZLIG TTHL TTHF TCP4 UDP4 ADC0 NAT0 

Ещё команда копировать всю информацию о пользователе не копирует тэг пользователя, тэг -[RO][UWS][CTA]: <ApexDC++ V:1.6.0,M:P,H:9/0/0,S:3>

Вот ещё CMD скрины: http://savepic.net/8753385.png , http://savepic.net/8728809.png
подозрительные команды: 
$RevConnectToMe -[RO][UWS][CTA] AlienKeller
$MyINFO $ALL -[RO][UWS][CTA] $ $100=$$77687051084$

**Comment by pavel-pimenov** [comment]
"Ещё команда копировать всю информацию о пользователе не копирует тэг пользователя, тэг "
Исправил.
По спаму - пока можно залочить этот IP через меню.
или есть алгоритм как сделать это автоматом?

**Comment by Krulk** [comment]
Можно проверять у каждого IP частоту появления команды $MyNick, и например если в течении 10 сек приходит 10 таких команд, временно блокировать пользователя. -[RO][UWS][CTA] приставал ко мне с такой командой как раз 1 раз в секунду. 

Только я не знаю как часто и много эта команда приходит от IP нормальных пользователей в разных ситуациях и что -[RO][UWS][CTA] посылает после этой команды, сегодня он уже не пристаёт.

Ещё при обновлении клиента открывается хаб pretoriano.europeshare.net:2009 , но он уже есть у меня в избранных без 2009 и отлично открывается. Можно убрать 2009 из открываемого хаба чтобы он не добавлялся при обновлении клиента если он уже есть в избранных.

**Comment by pavel-pimenov** [comment]
1. Ок подумаю над блокировкой спама MyNick
2. про фильтрацию Ip подробнее.
![default](https://cloud.githubusercontent.com/assets/920705/21514277/6d206ede-ccd4-11e6-9084-d54bfc22a5c7.png)
3. про pretoriano.europeshare.net:2009 тоже можно завести отдельное issue с картинками. как мне это повторить? у вас две записи в избранных но с разными портами,? 411 и 2009?

**Comment by Krulk** [comment]
1. Похоже не надо блокировать спам MyNick, это не спам, это у меня включён автобан по шаре, http://savepic.net/8742993.png и юзер так пытается подключиться.

2. Фильтрация IP проверил работает, вопрос снимается.

**Comment by pavel-pimenov** [comment]
Спасибо.
