### ISSUE TITLE
Открываются лишние хабы

### ISSUE THREAD

**Issue by Krulk** [pavel-pimenov/flylinkdc-r5xx#1658]
При запуске FL (особенно после обновления) часто в конце в беспорядке открываются новые хабы:
dchub://jupiter.europeshare.net
dchub://gladiatore.europeshare.net:416
dchub://pretoriano.europeshare.net
dchub://pretoriano.europeshare.net:1209
dchub://pretoriano.europeshare.net:2009
dchub://dcmagnets.freeway-fun.net:414

http://savepic.net/8766572.png
Подключение этих хабов - это перенаправление с других хабов или просто их реклама в FL? Можно сделать их добавление отключаемым? Или после закрытия не открывать их до следующего обновления FL?

**Comment by pavel-pimenov** [comment]
рекламы тут точно нет.
а можешь залогировать CMD Debug в файл и показать что там по фильтру pretoriano?

**Comment by Krulk** [comment]
Скрин с фильтром pretoriano, $MyHubURL проскакивает очень редко:
http://savepic.net/8728687.png
Кусок лога c последнего запуска:
https://yadi.sk/i/heusLQQ935c3bA

**Comment by pavel-pimenov** [comment]
У флая добавлена фича - он помнит все открытые хабы которые активные и восстанавливает после перезапуска даже если их не добавили в фавориты (сделал по просьбе тех кто гуляет по хабам и потом при перезапуске теряет открытый список) тут и возник такой побочный эффект.
наверно нужно закрыть сохранения адресов которые получены перенаправлением.

пока попробуй следующее
запусти флай - закрой те лишний вкладки и снова перезапусти флай.
они ведь не появятся снова? или появятся?

**Comment by pavel-pimenov** [comment]
Вечером сделаю новую бетку - проверите на ней
не должны больше восстанавливаться фантомные закладки от редиректов.
если все хорошо - закроете issue

**Comment by pavel-pimenov** [comment]
Жду от вас теста бетки.

**Comment by Krulk** [comment]
Лишние хабы перестали открываться, спасибо.
