### ISSUE TITLE
Список интернет хабов, 2 непонятных нюанса

### ISSUE THREAD

**Issue by RoLex** [pavel-pimenov/flylinkdc-r5xx#1660]
`[12:08:02] <RoLex> не понял ... из флая выпилили ручное добавление xml хаблистов ???`
`[12:09:32] <RoLex> а еще в флае только список российских хабов с моего сайта ???`
`[12:10:34] <OneRuN> видать смотрит по бывранному языку, у меня тоже только русские подгрузились`
`[12:10:49] <OneRuN> языку клиента*`
`[12:11:06] <RoLex> не, там есть список итальяшки`
`[12:11:14] <RoLex> а dchublist.com только русский`
`[12:11:16] <RoLex> лооол`
`[12:11:31] <RoLex> бля, может мой конфиг такой ?`
`[12:11:40] <OneRuN> у ску все хабы показывает ггг`
`[12:11:41] <RoLex> щас с нуля тестану`
`[12:11:44] <OneRuN> у меня так же`
`[12:22:47] <RoLex> вот все мои списки (смотри вверх экрана а потом вниз экрана) > http://i.imgur.com/huxupzn.png`
`[12:23:20] <RoLex> а вот все списки которые использует флай (по умолчанию, и изменить нельзя) > http://i.imgur.com/cJNfvdI.png`
`[12:25:37] <RoLex> это говорит о том что клиент ограничен только для российских пользователей? если да то почему списки флекса и ску общие/всех стран?`
`[12:25:54] <RoLex> .. если нет то почему нет моего общего списка ?`
`[12:26:11] <OneRuN> да просто ошибся наверно`
`[12:27:48] <RoLex> и третий вопрос .. почему эти списки нельзя руками редактировать пользователю? в любом клиенте всегда существовал такой функционал, т.к у каждого свои фавориты (хабы и списки хабов)`
`[12:28:37] <RoLex> FlylinkDC-dev: ответишь ?`
`...`
`[12:54:21] <RoLex> HackFresse: я бы понял что в флае только русские интернет хабы если бы небыло других общих (флекс и итальяшка), но тогда напрашивается вопрос: значит флай только для русскоязычных пользователей? т.к другой иностранец теперь не может добавить в флай иностранные хаблисты и пользоваться ими т.к эта фича была выпилена ))`
`[12:54:39] <RoLex> вобще не понимаю логику`

**Comment by pavel-pimenov** [comment]
я вырезал список жестко зашитый в коде С++ (в оригинальном ДЦ++ много вообще мертвых списков)
теперь он подгружается динамически из конфига.
какие нужно добавить - пишите

**Comment by RoLex** [comment]
Вот этот надо добавить: http://www.te-home.net/?do=hublist&get=hublist.xml.bz2
Так как вот этот носит в себе только российские хабы: http://www.te-home.net/?do=hublist&get=hublist-ru.xml.bz2

**Comment by pavel-pimenov** [comment]
перегрузи флай. добавил.
а зачем в том списке дубли из ру?
![default](https://cloud.githubusercontent.com/assets/920705/22854384/9482a640-f07e-11e6-8488-7d1bc3c664b6.png)

**Comment by RoLex** [comment]
Спасибо.

> а зачем в том списке дубли из ру?

Не понял вопроса, обьясни плиз.

**Comment by pavel-pimenov** [comment]
Если разделения по странам у тебя уже есть 
может имеет смысл сделать вложенное дерево
где будет уже детализация Ru,UA, т.д.

**Comment by RoLex** [comment]
Ты не подумал о том что другие клиенты не умеют вложенное дерево. Этот список хабов для всех, не только для флая. Спасибо, вопрос закрыт.
