### ISSUE TITLE
FL находится вне экрана

### ISSUE THREAD

**Issue by Krulk** [pavel-pimenov/flylinkdc-r5xx#1662]
При использовании 2 мониторов (монитор и ТВ) и переключении основного монитора между ними, FL при некоторых настройках при старте остаётся вне обоих мониторов и достать его методом "Переместить окно" не получается. В панели задач и трее значок FL при этом есть.
Вроде недавно были правки связанные с положением FL на нескольких мониторах и вылет вне поля мониторов должен быть исключён но FL всё равно вылетает вне поля.

Чтобы FL выпал вне поля надо:
- есть 2 монитора второстепенный слева | основной справа
- запускаем FL на основном
- меняем статус мониторов, основной теперь слева, второстепенный справа
- закрываем FL
- меняем статус мониторов на исходный второстепенный слева | основной справа
- запускаем FL. FL запустился но его экран смещён вправо, а справа от основного экрана ничего нет и достать FL оттуда просто так не получится, приходится переключать мониторы, тогда FL оказывается на второстепенном мониторе справа и его оттуда переместить на основной экран налево, потом переключить экраны в исходное положение.

Панель управления Nvidia при этом тоже оказывается смещённой вправо и не достаётся, но если её закрыть и открыть, то она открывается посередине основного монитора, то есть она каждый раз запускается на основном мониторе. FL же так и остаётся вне поля основного монитора.

**Comment by SCALOlaz** [comment]
В меню FL в трее пункт "Расположить окно по центру основного дисплея" пробовали нажимать?

**Comment by Krulk** [comment]
Нажал, окно FL переместилось в центр, всё нормально. Только у меня этот пункт не переведён и перемещение работает когда окно FL открыто, когда оно закрыто FL никак не реагирует.

Ещё после каких-то обновлений окно FL всегда запускается в окне, хотя при закрытии оно было на весь экран, а раньше нормально запускалось во весь экран, не удобно.
