### ISSUE TITLE
Поиск ищет торренты, хотя они отключены в настройках

### ISSUE THREAD

**Issue by Krulk** [pavel-pimenov/flylinkdc-r5xx#1665]
r505-beta-x64 build 20740
Поиск ищет торренты, хотя они отключены в настройках.
Ещё поиск уже месяца 2 часто подвешивает весь FL секунд на 5-10. Торренты отключены. Раньше такого не было, жмёшь enter и окно сразу начинало заполняться результатами.

**Comment by pavel-pimenov** [comment]
Спасибо. принято. поправлю завтра. оставайтесь на связи.
также если не сложно пишите о проблеме сразу как заметите - 2 месяца ждать не нужно. )

**Comment by pavel-pimenov** [comment]
Исправлено с build 20749 и выше - ожидайте в авто-обновлении.
