### ISSUE TITLE
Поиск торрентов работает неправильно

### ISSUE THREAD

**Issue by Krulk** [pavel-pimenov/flylinkdc-r5xx#1666]
Поиск торрентов ищет совпадение не всех слов из запроса, а совпадение любого слова из запроса считается верным результатом.
Например:
"Логан BDRemux" выдаёт все торренты с "Логан" и кучу лишних фильмов с "BDRemux"
"Логан 2017" выдаст все торренты с "Логан" и все файлы с "2017", какую-то музыку 2017 и хз. что.
В общем чем больше слов в поисковой фразе, тем длиннее список найденного, хотя должно быть наоборот.

С предыдущим isue всё хорошо, при отключенном поиске торрентов теперь и поиск dc не тормозит.

**Comment by pavel-pimenov** [comment]
Да, я знаю о такой проблеме
поправил перезапустите флайлинк - проверьте.

![default](https://cloud.githubusercontent.com/assets/920705/26528959/74db6fea-43bf-11e7-90c9-77064c02a600.png)

но тут есть побочный эффект - если отпечататься в одном слове, то вообще ничего не найдется.
и я пока не знаю что лучше.

**Comment by Krulk** [comment]
С опечаткой и в DC не найдёт, ещё плохо что ищешь например "Логан 2017", а "Logan 2017" естественно не выдаёт. Но эти особенности должны быть всем и так понятны.
