### ISSUE TITLE
Не качать файлы, которые были загружены ранее

### ISSUE THREAD

**Issue by pavel-pimenov** [pavel-pimenov/flylinkdc-r5xx#1667]
Есть ли возможность не скачивать файлы, которые ранее были скачены, но их нет в шаре или в папке закачки?
Например, если скачал 100 файлов mp3 у одного пользователя, послушал, удалил их,
а потом качаешь папку из 500 файлов mp3 у другого пользователя, среди которых есть эти 100 файлов,
как скачать только 400 новых, не выделяя их вручную?
Вручную это становится затруднительно, если эти 100 файлов разложены по подпапкам. В таком случае нужно заходить в каждую из них, выбирать только новые файлы, и указывать для каждой путь для сохранения. Хотелось бы иметь возможность добавить всю папку с подпапками в закачку, проигнорировав при этом ранее скачивавшиеся файлы, которых физически уже нет.

**Comment by petrovi4** [comment]
+1

**Comment by petrovi4** [comment]
Эта задача еще не запланирована на конкретный релиз? Очень не хватает такой возможности ((

**Comment by pavel-pimenov** [comment]
Ок. оставайтесь тогда на связи 
я постараюсь сегодня вечером сделать тест
сможете проверить в действии?

**Comment by petrovi4** [comment]
Павел, я на связи. Как будет сборка, кидайте ссылку на закачку, как можно оперативнее проверю.

**Comment by pavel-pimenov** [comment]
@petrovi4 вечером будет новая бетка. спасибо за тестирование.

**Comment by pavel-pimenov** [comment]
Проверьте. галкой включается функция. (по умолчанию выключена.)
![default](https://user-images.githubusercontent.com/920705/31285176-598b4c5e-aac3-11e7-9866-409249c9a685.png)

**Comment by petrovi4** [comment]
В целом - работает. 
Скачал, удалил файл с диска. Ставлю на закачку ту же папку повторно - в очереди она не появляется. Тут все ок.
Но если удалить запись о файле из списка завершённых закачек, повторная закачка всё равно не производится. Т.е. похоже, что приложение где-то еще сохраняет список ранее закачанных файлов, и не ориентируется на список, который доступен пользователю.
Было бы здорово, чтобы если стоит галка "Пропускать ранее скачанные файлы", то тот факт, что файл был скачан ранее брался из списка "Завершенные скачивания", из которого, при необходимости, файл можно и убрать, если все таки нужно закачать файл повторно.

**Comment by pavel-pimenov** [comment]
Да. факт загрузки файла берется из tth-history.leveldb (по ней же идет подкраска)
с удалением - понял. вечером прикручу поиск по той таблице

**Comment by pavel-pimenov** [comment]
Обновись до билда 21011 - проверь. все ок?

**Comment by petrovi4** [comment]
Обновился до 21013 - работает чётко!
Отлично, спасибо!

**Comment by pavel-pimenov** [comment]
ок. пишите еще issue или находите из архива что важно для вас.
