### ISSUE TITLE
Ищет каждое слово, вместо фразы

### ISSUE THREAD

**Issue by Krulk** [pavel-pimenov/flylinkdc-r5xx#1668]
r505-beta-x64 build 20804
FL стал искать каждое слово в поисковой фразе отдельно и выдаёт слишком много совпадений. Torrent и DC одинаково. Надо чтобы искал фразу целиком, пусть даже не последовательно.

А, нет он ищет каждое слово в фразе в путь\имя файла. Но раньше было не так?

**Comment by pavel-pimenov** [comment]
Можно пример таких слов и скрин?

**Comment by Krulk** [comment]
http://i93.fastpic.ru/big/2017/0622/5d/330d1fc5274d32871e1ce50da8d3f65d.png
Вот ищет каждое слово в фразе не последовательно в путь\имя файла, раньше вроде искал только последовательное совпадение а не беспорядочное, поэтому было меньше результатов, хотя не уверен.

**Comment by Krulk** [comment]
В общем всё вроде нормально, ложная тревога.
