### ISSUE TITLE
Отсутствует перевод строк, которые переведены на Transifex

### ISSUE THREAD

**Issue by adem4ik** [pavel-pimenov/flylinkdc-r5xx#1670]
**Установленная версия:** r504-x64 build 20844 (последняя стабильная)
**Автообновление:** Включено, в т.ч. для "Языкового модуля"
**Язык:** Русский
**Transifex:** Строка компонента "Translations the UI" "Attach a program window on center Master Monitor" переведена как "Прикрепить окно программы к центру главного монитора"

1. Запускаем программу
2. Правый клик по иконке в трее

**Результат:** Предпоследний пункт меню отображается как "Attach a program window on center Master Monitor"
**Ожидаемый результат:** Предпоследний пункт меню отображается как "Прикрепить окно программы к центру главного монитора"

Аналогичная ситуации со множеством других строк, перевод которых есть на Transifex.

**Comment by pavel-pimenov** [comment]
Спасибо. есть такая проблема. изменения из Transifex не переносятся автоматом в проект.

**Comment by pavel-pimenov** [comment]
Автообновите клиента - проверьте. все ок?

**Comment by adem4ik** [comment]
Клиент обновил до r504-x64 build 20854, большинство строк теперь переведено. Спасибо! Заметил лишь единственную отсутствующую строку:
<string name="LastRecentHubs">Последние открытые хабы</string>

**Comment by pavel-pimenov** [comment]
Спасибо. "Последние открытые хабы" увидел - тоже перенес.

**Comment by pavel-pimenov** [comment]
А перевод вы делали.? я там нашел опечатку 
<String Name="SettingsSpeedsNotAccurate">Примечание: скорость определяется не на 100% aточно…</String>

**Comment by adem4ik** [comment]
Переводом активно занимаюсь, но данную строку переводил не я. Исправил.
>Примечание: скорость определяется не на 100% aточно…
>by NightOrion, 8 months ago

**Comment by pavel-pimenov** [comment]
Спасибо. в след авто-обновлении будут последние правки.
нужно будет подумать как лучше подписаться на появление изменений.
пока приходится руками сравнивать...
