### ISSUE TITLE
Статус скачки отображается без подробностей

### ISSUE THREAD

**Issue by Krulk** [pavel-pimenov/flylinkdc-r5xx#1671]
Надо добавить более подробную расшифровку почему невозможно скачать файл.

В FL если файл невозможно скачать его статус "Тайм-аут соединения", другие клиенты нормально отображают причину, пример:
FL: http://f6.s.qip.ru/qpjF8Ug2.png
Apex: http://f1.s.qip.ru/X3XjlhWo.png
Grey: http://f1.s.qip.ru/w5qyEIrL.png
Strong: http://f6.s.qip.ru/9EAwnyRM.png
Пишут:
Нет слотов - В очереди: 123
Все слоты скачки заняты
в каком-то клиенте давно даже видел, что пишет я забанен юзером. FL в этом случае наверняка напишет "Тайм-аут соединения" и всё.

Ну и старт скачки при запуске FL и после переподключения к хабу по прежнему не работает, или очень редко.

**Comment by pavel-pimenov** [comment]
Принято. извини немного не хватает времени быстро отвечать - лето :)

**Comment by pavel-pimenov** [comment]
Спасибо за ожидание! это баг тоже нашел вчера вечером - ожидайте в автообновлении.

**Comment by pavel-pimenov** [comment]
Автообновитесь на канале бета - все станет ок?

**Comment by Krulk** [comment]
Да стало лучше, статусы начали отображаться (как и было давно). Но они отображаются не на всех стоящих на закачке файлах, это уже другая проблема.

Это исправление (возможно) помогло мне найти проблему из другого Isules, где файлы не удалялись с диска при удалении из закачек. Статус закачки "Папка для временных файлов недоступна: Недостаточно места на диске.[error: 112]"

**Comment by pavel-pimenov** [comment]
Спасибо за помощь в тестировании.
