### ISSUE TITLE
This is normal?

### ISSUE THREAD

**Issue by Havokdan** [pavel-pimenov/flylinkdc-r5xx#1672]
Good morning, I would like to describe a situation that happens to me, that I do not know if it is the correct behavior of the program or not, come on:

1 - My connection settings are working normal, I search, I find several files of a user as a result;

2 - For example, I select five files from this user to download, the download of one of them begins immediately, the others I imagine that go to the queue;

3 - The download of a file ends, but the following never starts, I initially thought I was in the queue, until I closed it and opened the program again, the download started immediately, hence discovering that the application only downloads one file at a time, Then just start another if I close and open again.

Is this expected behavior? I have a problem? I'm sorry, I can understand English a bit, but to speak I use Google Translate.

I'm using Windows 10x64 and the Flylinkdc++ version is r504-x64 build 20887

**Comment by pavel-pimenov** [comment]
FlylinkDC bug :-(

**Comment by pavel-pimenov** [comment]
try build 20903 ? (menu->help->update check)

**Comment by Havokdan** [comment]
I just tested and the problem is solved, thank you very much.
