### ISSUE TITLE
Несколько улучшений по журналам

### ISSUE THREAD

**Issue by Krulk** [pavel-pimenov/flylinkdc-r5xx#1675]
- Сделать по-умолчанию имя папки для различных логов не %B - %Y а %Y-%m:
было:
PM \ %B - %Y \ %[userNI]-%[hubURL].log
сделать:
PM \ %Y-%m \ %[userNI]-%[hubURL].log
это упорядочит папки в проводнике по возрастанию года и месяца, а не как сейчас, в беспорядке по алфавиту

- писать игнорируемые от хаба или ботов лички не в System.log а в папку PM как обычные лички, можно даже сделать отдельную галку в настройках Журналов для таких сообщений. Сейчас System.log забивается всяким хламом типа:
[2017-09-09 20:50:28] Ignore PM: from user: Genio on hub: dchub://caos.europeshare.net:418 Message: . . . . . . . куча ANSI-графики
[2017-09-09 20:54:53] NmdcHub::toParse $To: invalid user: rtNick = Genio param = AlienKeller From: Genio $<Genio>
. . . . . . куча ANSI-графики
[2017-09-09 20:42:48] Ignore PM: from user: Информатор on hub: dchub://xn-----jlcbvlafgtg4jvd.xn--p1ai. Message:
[2017-09-17 20:29:08] Ignore PM: from user: FastStorm on hub: dchub://europehub.freeway-fun.net:415 Message: *
Пример System.log забитого такими сообщениями: https://yadi.sk/i/Ffmj7UoB3MkHDi

**Comment by pavel-pimenov** [comment]
1. По логам - в этой части уже кстати делались правки
https://github.com/pavel-pimenov/flylinkdc-r5xx/blob/c4058f727481d0752be8bc7f6d42f7a4293c14db/client/SettingsManager.cpp#L1655
2. Отдельную галку не буду делать - скрину в лог PM
в системный лог кидал данное сообщение т.к. его видно в окне статуса даже если выключено логирование в файл.

**Comment by pavel-pimenov** [comment]
@Krulk можете проверить вот этот билд https://yadi.sk/d/Pp8lX2E33N6ejk

			const string l_template_pm_folder = "PM\\%B - %Y\\";
			if (key == LOG_FILE_PRIVATE_CHAT && l_new_value.find(l_template_pm_folder) != string::npos)
			{
				l_auto = false;
			    boost::replace_all(l_new_value, l_template_pm_folder, "PM\\%Y - %m\\");
				strSettings[key - STR_FIRST] = l_new_value;
			}
1. Должен править старый шаблон автоматом
2. Логи в PM тоже перекинул

если все ок - отпишите выпущу обновление для всех.

**Comment by Krulk** [comment]
1. Логи теперь где нужно, но лучше убрать пробелы и сделать %Y-%m. Это сделает папки больше похожими на часть такого шаблона: 2017-09-08 19-48-15

2. Большая часть сообщений от ботов теперь пишется в PM как нужно, System.log сильно разгрузился, но в нём проскакивают такие сообщения:
[2017-09-21 18:11:03] NmdcHub::toParse $To: invalid user: rtNick = BOT param = AlienKiller From: BOT $<BOT> 
[2017-09-21 18:11:04] NmdcHub::toParse $To: invalid user: rtNick = °•-MegaReg-•° param = AlienKiller From: °•-MegaReg-•° $<°•-MegaReg-•°>
[2017-09-21 18:11:04] NmdcHub::toParse $To: invalid user: rtNick = Genio param = AlienKiller From: Genio $<Genio> куча ANCI графики

связаны с тем, что я не зарегистрирован на этих хабах, им тоже нечего делать в System.log

**Comment by pavel-pimenov** [comment]
А куда кидать NmdcHub::toParse ?

**Comment by Krulk** [comment]
Это вроде тоже личные сообщения от ботов, я думаю кидать в PM. Лучше там будет мусорка чем в System.log. А чтобы мусорки не было, лучше добавить галку не логировать личные сообщения от ботов.
Или ещё видел в каком-то клиенте вариант скидывать эти сообщения от ботов прямо в чат хаба. Тогда если логирование чата хаба выключено, они тоже не будут сохраняться. Но этот вариант не нравится, лучше галка :)

**Comment by pavel-pimenov** [comment]
Обновитесь. все ок?

**Comment by pavel-pimenov** [comment]
1. По умолчанию сделал везде %Y-%m - просто конвертацию автоматом не добавлял.
2. Про точки понял - там поиск заменой не получится. локализация загружается из внешнего сайта. но я подумаю как это сделать. а чем три точки лучше? можно пример?

**Comment by pavel-pimenov** [comment]
https://github.com/pavel-pimenov/flylinkdc-r5xx/commit/0758240efcb125b4ff9f0b8def88baad8a6c7641

**Comment by Krulk** [comment]
Сохранение личек от ботов и хабов практически невозможно отключить, диск изрядно забивается ~1мб/день. Можно их привязать к галке Журнал личных сообщений?

По факту они уже к ней привязаны, когда галки "Игнорировать приватные сообщения от хабов\ботов" не стоят, тогда открывается куча личек но они не сохраняются, если галка "Журнал личных сообщений не стоит". А в скрытом виде лички от хабов\ботов почему-то сохраняются в любом случае.
