### ISSUE TITLE
Отключить сохранение личек от хабов и ботов

### ISSUE THREAD

**Issue by Krulk** [pavel-pimenov/flylinkdc-r5xx#1677]
Сохранение личек от хабов/ботов практически невозможно отключить, \PM изрядно забивается ~1.5мб/день (зависит от количества хабов и переподключений). Можно их привязать к галке "Журнал личных сообщений"? В отключенном виде лички от хабов/ботов почему-то сохраняются в любом случае. А когда они включены, то галка "Журнал личных сообщений" нормально отключает их сохранение, как и обычных личек.
Нужно, чтобы галка  "Журнал личных сообщений" отключала/включала сохранение личек от хабов/ботов в любом виде, включены они или нет.

**Comment by Krulk** [comment]
Вот файлы логов от ботов и хабов за октябрь, 22Мб, 216 файлов:
![2017-11-03_000829](https://user-images.githubusercontent.com/13403998/32350366-39f9f91c-c02b-11e7-8b5e-a0b44297dd2b.png)
Выбраны такие системные логи:
![2017-11-03_001105](https://user-images.githubusercontent.com/13403998/32350484-8e695eac-c02b-11e7-8a28-5d7a62e4a660.png)
а логи от ботов и хабов всё равно записываются на диск.

**Comment by pavel-pimenov** [comment]
ок. спасибо. на выходных я повторю эту проблему исправлю.

**Comment by pavel-pimenov** [comment]
у меня не повторяется - при одной галке создается только один файл
![default](https://user-images.githubusercontent.com/920705/32360836-a9bfbb26-c06a-11e7-8ef6-caf6327b15c0.png)

**Comment by Krulk** [comment]
Надо поставить галки: Игнорировать приватные сообщения от хаба/бота, перезапустить FL:
![2017-11-03_082510](https://user-images.githubusercontent.com/13403998/32361353-915f7df4-c070-11e7-9d3f-6f3561cb1d28.png)

**Comment by pavel-pimenov** [comment]
ок. эти галки я не пробовал - проверю.
но из-за них не должны порождаться файлы... это явный баг.
