### ISSUE TITLE
Добавить возможность не качать известные файлы: пропускать файлы, которые есть в шаре; которые были в шаре

### ISSUE THREAD

**Issue by ALEKSEY1232321** [pavel-pimenov/flylinkdc-r5xx#1680]
Спасибо вам за функцию в настройках "Пропускать ранее скачанные файлы".

Есть ещё два типа известных файлов, которые можно было бы не скачивать.
Это файлы, которые:
- Расшарены (какой смысл их скачивать, если они итак есть на диске).
- Которые были в шаре ("Этот файл был у меня в шаре..."), но не были скачаны через DC++.

Если сможете, сделайте пожалуйста в настройках галочки и для этих вариантов.

**Comment by pavel-pimenov** [comment]
"Расшарены (какой смысл их скачивать, если они итак есть на диске)."

По поводу этой галки - есть момент 
такая галка была раньше во флае, но она дает побочный эффект:
Если вы качаете DVD диск россыпью то там есть файлы которые одинаковые для других DVD дисков.
в результате скачанный образ будет без нужных файлов и окажется битым.

Верну ее.
было в планах сделать как в грее - чтобы файл копировался из шары в новое место вместо закачки.
возможно так и стоит сделать...

Ожидайте вечером тест сборку с галками.

**Comment by pavel-pimenov** [comment]
Проверьте на канале - бета. все ок?

**Comment by ALEKSEY1232321** [comment]
При включении галочки "Не скачивать файлы ранее находившиеся в вашей шаре", файлы которые "находятся в шаре сейчас", также не качаются. По факту получается:

Не скачивать файлы находящиеся в вашей шаре
Не скачивать файлы находящиеся и ранее находившиеся в вашей шаре

Если файлы "находящиеся в шаре сейчас" невозможно убрать из базы "бывших в шаре", то корректней просто переименовать опцию.

**Comment by ALEKSEY1232321** [comment]
И ещё один тип файлов, которые хотелось бы исключить:
Файлы, которые уже есть в очереди скачивания.

Если добавить на скачивание папку с файлами, а затем добавить её же в другой путь сохранения, то эти файлы скачаются два раза. Такая же ситуация может быть при добавлении папок с разных пользователей, если часть файлов в них совпадает. 

Хотелось бы, чтобы файлы, которые уже есть в очереди, не добавлялись в закачку. И в то же время желательно, чтобы этот новый источник добавлялся к уже имеющемуся файлу в очереди.

**Comment by pavel-pimenov** [comment]
1. Добавил проверку на файлы из шары.
если будет стоять галка "Не скачивать файлы ранее находившиеся в вашей шаре"
то файлы которые сейчас находятся в ней будут качаться - так устроит?
2. Про очередь понял - добавил проверку (без галки)

**Comment by ALEKSEY1232321** [comment]
1. Если при включении одной из опций получается так:
Не скачивать файлы находящиеся в вашей шаре (но не ранее находившиеся в вашей шаре)
Не скачивать файлы ранее находившиеся в вашей шаре (но не находящиеся в вашей шаре)
А при включении обеих опций получается так:
Не скачивать файлы находящиеся в вашей шаре и ранее находившиеся в вашей шаре
То программа работает так, как и задумано в настройках.

2. С очередью может быть указанная вами сложность, если дубликаты будут в виде связанных системных файлов. Большинство файлов, которые не связаны с другими, это не коснётся, к примеру avi, mp3, pdf. 

Но если это к примеру распакованный мультимедийный диск или программа, в которой есть несколько одинаковых файлов, или серия htm файлов с папками, в каждом из которых есть одинаковое изображение, то получится, что скачается только один из файлов. То же и с DVD.
Если добавить несколько DVD, то получится, что системный файл скачается только в одну папку.

Возможно имеет смысл вынести эту опцию отдельно.

**Comment by ALEKSEY1232321** [comment]
1. На практике попробовал отключить каждую из трёх опций. При добавлении всех известных файлов только отключённый тип файлов добавлялся в очередь скачивания. В общем как и задумано.
2. При отключении всех опции и добавлении в очередь папки DVD с серией одинаковых файлов добавился только один из этих дубликатов файлов.

**Comment by pavel-pimenov** [comment]
Считаем что все ок. и закрываем проблему?
