### ISSUE TITLE
Тест UDP порта

### ISSUE THREAD

**Issue by ss5dc** [pavel-pimenov/flylinkdc-r5xx#1681]
Добавьте пожалуйста возможность отключить тест UDP порта при поиске. Несмотря на корректно проброшенные порты, тест не проходится - из-за чего ищет в пассивном режиме.

**Comment by ss5dc** [comment]
Как выяснилось, сервер для теста блокируется программой "PeerBlock"

**Comment by pavel-pimenov** [comment]
Если порт закрыт, то вам не будут приходить поисковые ответы.
в пассивном режиме хоть что-то будет находится

**Comment by ss5dc** [comment]
Порт открыт, однако отсутствует связь с с сервером для теста. В моём случае предположительно сервер оказался в списке программы "PeerBlock", однако возможны другие причины отсутствия связи с конкретным хостом (тот же дидос и пр.). Также такая "авто-пассивация" может быть вредной для локальных сетей.

**Comment by pavel-pimenov** [comment]
Запустите флай с ключем FlylinkDC_x64.exe /notestport
будет все ок?

**Comment by ss5dc** [comment]
Да, ништяк. Результаты поиска приходят от клиентов, насколько я понял.
`18:42:51 Client:	[Incoming][128.68.0.106]	 	[Search-result] url = dchub://dc.fly-server.ru remoteIp = 128.68.0.106 file = !films\!2017\Оно (Кинг) [It.2017.Dc.CAM.KS4].mkv user = [bog]KANO
18:42:51 Client:	[Incoming][176.121.167.59]	 	[Search-result] url = dchub://dc.fly-server.ru remoteIp = 176.121.167.59 file = P:_\Кинокартины\Сердце дракона IV. Драконорождённый. (2017г.).avi user = Hammer-65
18:42:51 Client:	[Incoming][176.121.167.59]	 	[Search-result] url = dchub://dc.fly-server.ru remoteIp = 176.121.167.59 file = J:_\КиноВидеоФильмы\Оно приходит ночью. (2017г.).mkV user = Hammer-65
18:42:51 Client:	[Incoming][217.25.213.211]	 	[Search-result] url = dchub://dc.fly-server.ru remoteIp = 217.25.213.211 file = Видео\Фильмы\Новая папка\Оно It [2017,ужасы, драма,TS) Hub-hmn.pp.ru.avi user = megamind`
Хотя несколько смущает надпись "[AutoPassive]" в окне поиска в серой строке под результатами.

**Comment by pavel-pimenov** [comment]
поправил надпись - будет в след обновлении.

		if(g_DisableTestPort)
			g_last_search_string += " [DisableTestPort]";
		else
		if (p_search_param.m_is_force_passive_searh)
			g_last_search_string += " [AutoPassive]";
