### ISSUE TITLE
Не начинает качать файлы после перезапуска #2

### ISSUE THREAD

**Issue by Krulk** [pavel-pimenov/flylinkdc-r5xx#1682]
FL снова не начинает качать файлы после перезапуска. Если сделать поиск альтернатив, то качать этот файл начинает, а другие нет. Приходится проходиться поиском по всем файлам.

**Comment by pavel-pimenov** [comment]
какой номер билда так стал снова делать сможете подсказать?

**Comment by pavel-pimenov** [comment]
не повторилось - после перезапуска сам находит альтернативу и начинает качать.

**Comment by Krulk** [comment]
Чтобы совсем не качал повторить пока не удалось. Но выявил другое: если у файла 1 источник, то после старта FL начинает качать с задержкой 60 секунд; если 2 и более источников, то начинает качать сразу. Задержка 60 сек обязательна?

**Comment by pavel-pimenov** [comment]
нет, она не обязательна. другие ведь клиенты ее не делают.
я проверю с несколькими источниками.

**Comment by Krulk** [comment]
Понял почему начинает качать после 60 сек после запуска. При включённом "Поиск альтернативных источников каждые 10мин" через 1 мин после запуска ищет альтернативы, поэтому начинает качать. Если выключить, то качать файлы с 1 источником после запуска не начинает совсем в большинстве случаев. Если сделать вручную поиск альтернатив, то когда находит 1 юзера с этим фалом тутже начинает его качать.

В качестве фала с 1 источником использую в поиске Аватар 20000мб Видео. Или например такой TTH: 5MFYCDTVRVMK3564RXQYJ5AIJMRJXUZAIGZ5RYA

**Comment by pavel-pimenov** [comment]
Обновитесь до 21203. там будет все ок?

**Comment by Krulk** [comment]
В 21203 всё нормально, качает сразу. Это важное исправление. Большинство музыки у юзеров в 1 экземпляре и сотни файлов закачивались неделями, т.к. при перезапуске не качались. Теперь качаются без проблем.

**Comment by pavel-pimenov** [comment]
спасибо.
