### ISSUE TITLE
Качал фильм 7 гигов, качало его минут 30, по итогу программа скачала чего-то на 21 гиг

### ISSUE THREAD

**Issue by PapIK1122** [pavel-pimenov/flylinkdc-r5xx#1692]
Качал фильм 7 гигов, качало его минут 30, по итогу программа скачала чего-то на 21 гиг
![image](https://user-images.githubusercontent.com/34656047/34115252-257ac1e6-e426-11e7-96b0-16e89d6b7611.png)

**Comment by pavel-pimenov** [comment]
Не заметили с какого номера билда такое началось?

**Comment by PapIK1122** [comment]
Ой, давно... мне кажется давно. Он уже давно не работает, как лет так 5 назад)

**Comment by Krulk** [comment]
А у меня наоборот, пишет меньший объём. Например скачал файл 8мб, а засчитывается только 2,44мб. Из колонки "Сетевой трафик"

![2017-12-18_210010](https://user-images.githubusercontent.com/13403998/34120375-7cc7f5e4-e436-11e7-9dd9-185bd63f19ad.png)

**Comment by pavel-pimenov** [comment]
Сетевой траф - действительно левый и значительно меньше чем должен быть.
я вчера скачал в тесте один тестовый файл (рис)
но суммарный размер трафа правильный.
Осталось повторить превышение.
если  это счетчик врет - починю.
а если действительно перекачивает лишние секции по несколько раз ... то это критично.
кто поможет повторить проблему с перекачкой?

![default](https://user-images.githubusercontent.com/920705/34288955-1c120e2e-e701-11e7-953f-a987818efc46.png)

**Comment by PapIK1122** [comment]
Оно когда качало, писало что скорость скачивания 10 МБ\сек, но по факту линия не заполнялась, а время загрузки только росло, в то время как "З:" показывало что оно довольно активно качает в данный момент. Оно действительно скачала мне фильм 3 раза.

**Comment by pavel-pimenov** [comment]
@PapIK1122 и у вас был один хаб? unet - киньте адрес. я попробую скачать то-же кино

**Comment by PapIK1122** [comment]
Один. Это сетевой хаб. Оттуда качать все в 10 раз дешевле. С интернета не качаю. dc.unet.by

**Comment by pavel-pimenov** [comment]
хм. у вас внутри сети тоже платный трафик. это плохо что флай так подставляет.
буду искать причину. с одним источником пока проблема не повторилась. 
я качал с компа внутри квартиры...

**Comment by PapIK1122** [comment]
Я качал трасформеры потом, вроде все было нормально. Все зависит от размера. Файлы больше 10 ГБ я больше не качаю, они у меня куда-то пропадают после окончания скачивания. Я даже программу переустанавливал - не помогало. Давно не проверял, может сейчас уже и нормально, но был такой момент. Когда я этого телохранителя для киллера качал, оно качало с 10 юзеров, я разворачивал и когда индикатор скачивания стоял на месте загрузка со всех шла, а он стоял. Просто был мертвый, но со всех качало, вот так было.

**Comment by pavel-pimenov** [comment]
Спасибо. сегодня вечером починю этот опасный баг. оставайтесь на связи.

**Comment by pavel-pimenov** [comment]
@PapIK1122  автообновитесь. проверьте - все стало ок?

**Comment by PapIK1122** [comment]
Ну потом протестирую, как фильм какой буду качать. Я не любитель фильмов. Не знаю когда проверю. Если что - напишу.

**Comment by pavel-pimenov** [comment]
Исправлено.
