### ISSUE TITLE
Как поставить в 4хх версию, поддержку уторрента?

### ISSUE THREAD

**Issue by dcbeelinekz** [pavel-pimenov/flylinkdc-r5xx#1694]
Самая стабильная уже 5 лет сижу это 414 Флайлинк, хотелось бы узнать как ее можно сделать еще красивее

**Comment by pavel-pimenov** [comment]
в r4xx поддержки торрентов никогда не будет - она заморожена.
но можно рядом поставить r5xx

**Comment by dcbeelinekz** [comment]
Паш, а исходников нету этой версии?

**Comment by pavel-pimenov** [comment]
414 ? есть.

**Comment by dcbeelinekz** [comment]
Да)) если есть в облаке ? И хотел узнать Мини UPnP на нее сложно поставить?

**Comment by pavel-pimenov** [comment]
На выходные залью ветку r4xx на github

**Comment by dcbeelinekz** [comment]
Спасибо, Паша )))
