### ISSUE TITLE
При открытии окна поиска показываются новинки торрентов, когда поддержка торрентов отключена

### ISSUE THREAD

**Issue by adem4ik** [pavel-pimenov/flylinkdc-r5xx#1696]
Условие: Настройки - Настройки соединения - Включить торрент - галка снята

1) Запустить Flylink DC++
2) Открыть окно поиска

Результат: Показываются новинки торрентов (http://www.flylinkdc.ru/2017/12/blog-post.html)
Ожидаемый результат: Список поиска пуст, до тех пор пока пользователь сам не соизволит что-то искать

**Comment by pavel-pimenov** [comment]
И закачка идет?

**Comment by adem4ik** [comment]
Да, если кликнуть на один из торрентов, начинается загрузка метаданных, затем открывается окно "Download Torrent", и если нажать ОК, то загрузка начнётся.

**Comment by pavel-pimenov** [comment]
Плохо. спасибо. поправлю

**Comment by adem4ik** [comment]
Обновился до r504-x64 build 21415. В обновлении указано исправление этого бага. В окне настроек соединения появился пункт "Use torrent search". Даже если галка убрана - популярные новинки торрентов продолжают показываться.

**Comment by pavel-pimenov** [comment]
там галка про поиск
Rss - тут
![default](https://user-images.githubusercontent.com/920705/37866780-513e210e-2fa0-11e8-8153-549198851c1c.png)

**Comment by adem4ik** [comment]
@pavel-pimenov понял, спасибо за наводку

**Comment by lisiy365** [comment]
Добрый день! Перестал работать поиск торрентов.

![Image](https://github.com/user-attachments/assets/fca518e5-a5dd-4f65-a63b-357ff01269f5)
