### ISSUE TITLE
How do I disable torrent related features?

### ISSUE THREAD

**Issue by Havokdan** [pavel-pimenov/flylinkdc-r5xx#1700]
How do I disable torrent related features? I've cleared the "Enable Torrent" option, however when I open a search tab, it shows results from torrent sites, how do I disable it?

**Comment by Havokdan** [comment]
I did update, unchecked the new option to disable the search for torrents, however when I open the search window, the program still brings the results, this is negative for me, because I use a program for this, not to mention that it generates a certain lag in the window response.

**Comment by pavel-pimenov** [comment]
Autoupdate
![default](https://user-images.githubusercontent.com/920705/38161185-b4b4a5d2-34d2-11e8-8ebb-71aeec8dc5f9.png)
