### ISSUE TITLE
Problems in my hub.

### ISSUE THREAD

**Issue by Havokdan** [pavel-pimenov/flylinkdc-r5xx#1704]
Good morning, since the r504-x64 build 21498 application, I can not get into the adc hub I made that is in my favorites, nor through F2, could someone tell me what the problem is, I reinstalled the application and the previous versions come in, as well as AirDCPP and APexdc. Could someone show me help?

**Comment by pavel-pimenov** [comment]
URL adc hub?

**Comment by pavel-pimenov** [comment]
Fixed
