### ISSUE TITLE
Английский перевод

### ISSUE THREAD

**Issue by falcon4fun** [pavel-pimenov/flylinkdc-r5xx#1706]
Без ногами того, кто писал английский перевод. : ) 
Логичность кнопки зашкаливает. Долго думал, почему на кнопке Paused, а он хэширует.

https://gfycat.com/IllfatedPitifulArthropods

**Comment by pavel-pimenov** [comment]
Спасибо. 
а какой прогой такой ролик сняли?

**Comment by falcon4fun** [comment]
@pavel-pimenov ShareX. Давно юзаю. Удобный комбайн для скриншоток, гифок, видео.

Это профиль экспорта на gfycat. Если надо, вот настройки (: 
https://i.imgur.com/Oki66ID.png

Список возможных направлений:
https://i.imgur.com/uC9EgBQ.png

**Comment by pavel-pimenov** [comment]
Перевод поправлен. будет в след билде.
