### ISSUE TITLE
Серое окно хаба после запуска

### ISSUE THREAD

**Issue by Krulk** [pavel-pimenov/flylinkdc-r5xx#1707]
В r505-beta-x64 build 21507 после запуска окно последнего хаба пустое серое, раньше сразу был хаб. Если переключиться на другой хаб, то всё нормально.

![2018-05-10_140421](https://user-images.githubusercontent.com/13403998/39867091-f4ac4cfa-545b-11e8-8c08-3a1850b2d89e.png)

**Comment by pavel-pimenov** [comment]
Можете взять копию Favorites.xml - вырезать из него пароли если они там есть и прислать этот файл мне.?

**Comment by Krulk** [comment]
Переслал
