### ISSUE TITLE
Когда не работает сервер обновлений, FL долго запускается.

### ISSUE THREAD

**Issue by Krulk** [pavel-pimenov/flylinkdc-r5xx#1708]
14.05.18 кратковременно не работал сервер обновлений. FL стал долго запускаться ~60 сек, и долго закрываться (висит в процессах) ~ 90сек. Как только сервер заработал FL стал запускаться быстро. Process Explorer при долгом закрытии показывает:
![2018-05-14_175512](https://user-images.githubusercontent.com/13403998/40005509-bc27eafe-57a0-11e8-8549-fa5957f62841.png)
![2018-05-14_175540](https://user-images.githubusercontent.com/13403998/40005510-bc4e0fd6-57a0-11e8-95b3-ff2d1f775f4a.png)
Это нормально?

**Comment by pavel-pimenov** [comment]
Как это починить я пока не знаю. таймаут на загрузке точно стоит меньше 60 сек.
а вот закрытие починил - не должно быть теперь 90сек

**Comment by JeanPaulLucien** [comment]
@pavel-pimenov, где находятся функции, ответственные за запуск и проверку? Я посмотреть могу.
