### ISSUE TITLE
Файлы на паузе, а FL их качает

### ISSUE THREAD

**Issue by Krulk** [pavel-pimenov/flylinkdc-r5xx#1709]
Пример, у одного юзера качаю 3 файла:
- 2 на паузе, качается 1 и ещё 1 который на паузе.
- 2 на паузе, после скачивания 1 что не на паузе, начинают качаться 2 на паузе.

Качаю 1 файл, ставлю на паузу, он сбрасывает скорость Отключено..., но потом продолжает качаться.
Скорость увеличивается и уменьшается как при закачке. Время не обновляется.

![2018-05-17_215528](https://user-images.githubusercontent.com/13403998/40200960-5aad57b8-5a26-11e8-975d-8969d6408243.png)
![2018-05-17_225159](https://user-images.githubusercontent.com/13403998/40200963-5ad5b870-5a26-11e8-9d6e-00d4f32605d6.png)
![2018-05-17_225455](https://user-images.githubusercontent.com/13403998/40200965-5af933ea-5a26-11e8-932e-3bb333b2f781.png)

**Comment by JeanPaulLucien** [comment]
Может просто докачивает сегмент?
