### ISSUE TITLE
Не загружается при старте системы

### ISSUE THREAD

**Issue by Eremiteb** [pavel-pimenov/flylinkdc-r5xx#1711]
FlylinkDC r504-x64 build 21538. Windows 10 версия 1709 (сборка 16299.125) корпоративная, долгосрочная поддержка. Флайлинк запускается от имени администратора, в настройках интеграции автозагрузка стоит, в меню в автозагрузке есть.
Но не загружается при загрузке:) В журналах винды ничего.

**Comment by pavel-pimenov** [comment]
Сам не использую такой функционал.
проверил в виртуалке под XP - автозагрузка сработала.
если руками поместить в автозагрузку то работает?

**Comment by pavel-pimenov** [comment]
Покажите скрин окна настроек.
У вас при нажатии кнопки - текст меняется?

![default](https://user-images.githubusercontent.com/920705/40669644-18dc8892-6370-11e8-8f70-f48d3da51ac9.png)

https://github.com/pavel-pimenov/flylinkdc-r5xx/blob/6e88f4be02b3c73e9fbdc873f7f888372748b41e/windows/IntegrationPage.cpp#L153

**Comment by pavel-pimenov** [comment]
Еще вопрос зачем вы запускаете клиента под админом?
Нужно пускать под вашим юзером.
если прав не хватить он сам запросит эскалацию и запустить временно еще одну копию флая.
с ключикомм /installStartup
			WinUtil::runElevated(NULL, Util::getModuleFileName().c_str(), _isShellIntegration ? _T("/uninstallStartup") : _T("/installStartup"));

**Comment by Eremiteb** [comment]
Да, дело было в запуске от имени администратора. Обычно, при таком запуске нужно подтверждать запуск, а когда в автозагрузке, подтверждать некому. Закрываю запрос.
