### ISSUE TITLE
При щелчке правой по большой группе выделенных юзеров, FL подвисает и что-то обрабатывает.

### ISSUE THREAD

**Issue by Krulk** [pavel-pimenov/flylinkdc-r5xx#1712]
Если выделить много пользователей и щёлкнуть по ним правой кнопкой, FL надолго подвисает и начинает что-то обрабатывать.

**Comment by pavel-pimenov** [comment]
Если включить логирование sqlite - в sqlite.log много накидывает запросов после нажатия мышкой?
можете показать что в логе? 
у меня временно нет доступа самому проверить.

**Comment by Krulk** [comment]
Включил логирование sqlite. После подвисания FL:
FlylinkDC_log.sqlite - записей не добавляется.
sqltrace.log - записей не добавляется.
sqlite.log - у меня такого файла нет.

**Comment by pavel-pimenov** [comment]
Тогда странно. была версия что он в базу лезет по каждому юзера (чтобы достать инфу о последнем ip)
а сколько юзеров выделяешь и на сколько вешается?

**Comment by pavel-pimenov** [comment]
Расскажите какую функцию вы зовете для большого числа пользователей? Запросить IP? или что-то другое?

**Comment by Krulk** [comment]
Зависает ровно на:
15 сек, при щелчке правой по 10 PageDown - 250 юзеров
30 сек, при щелчке правой по 20 PageDown - 500 юзеров
Никаких функция больше не вызываю.

Видео: https://gfycat.com/FearfulHelpfulDodobird

**Comment by pavel-pimenov** [comment]
Спасибо. понял. а выделение большого числа юзеров для чего делается?
что хочется с ними сделать через меню?

**Comment by Krulk** [comment]
Ничего не хочу сделать, просто выделил. Если выделить всех юзеров, то зависает на долго, терпения не хватает дождаться пока отойдёт, но всё де отходит.

Ещё по Torrent, можно сделать, чтобы недокаченные торренты содержались в той же папке Incomplete как и не завершённые DC закачки. А не как сейчас в Downloads

**Comment by pavel-pimenov** [comment]
автообновите бетку
про торренты - ничего пока не менял.

**Comment by Krulk** [comment]
Проверил, теперь меню короткое, зато не зависает. Полезные пункты меню вроде на пропали.
