### ISSUE TITLE
Окна каналов и окна ботов

### ISSUE THREAD

**Issue by Eremiteb** [pavel-pimenov/flylinkdc-r5xx#1713]
Больше как пожелание... Я выбрал канал, который мне более интересен. Мне хотелось бы, чтобы при запуске он открывался. Но, во время работы открываются окна ботов от разных каналов с рекламой или информацией. При их закрытии активируется предыдущее окно, а оно уже может быть не с выбранным мной каналом. Интересно, у вкладок есть свойство - канал или пользователь или бот?

**Comment by SCALOlaz** [comment]
У вкладок есть такое "свойство": общий чат хаба или ЛС от его пользователей/ботов.
Чтобы при запуске не мешали ЛС от других хабов/ботов/юзеров, нужно эти другие хабы убрать из автоподключения: на вкладке нужного хаба сделать ПКМ, выбрать пункт "Убрать автоподключение"

**Comment by Eremiteb** [comment]
> 
> 
> У вкладок есть такое "свойство": общий чат хаба или ЛС от его пользователей/ботов.
> Чтобы при запуске не мешали ЛС от других хабов/ботов/юзеров, нужно эти другие хабы убрать из автоподключения: на вкладке нужного хаба сделать ПКМ, выбрать пункт "Убрать автоподключение"

Как создал пожелание, не наблюдал за темой, но... заметил, что у меня уже долгое время теперь нет сообщений от ботов каналов:) Совпадение?? Хмм... Закрываю.
