### ISSUE TITLE
How do I remove this?

### ISSUE THREAD

**Issue by Havokdan** [pavel-pimenov/flylinkdc-r5xx#1718]
As I remove what is highlighted in the image below, came along with the last update:

![Sem título](https://user-images.githubusercontent.com/6549729/54075079-65ecbb00-4279-11e9-994a-1479df70acc3.png)

**Comment by mikekmv** [comment]
Nothing personal, just business...

**Comment by Havokdan** [comment]
At least, that was optional ...

**Comment by SCALOlaz** [comment]
Раз уж появилась необходимость продвинуть работу супруги, можно было создать между чатом и окном передач небольшой кусок MDI, и там гулять хоть на всю ширину окна.
В текущей реализации, реклама ломает весь вид поля ввода текста в чат и кнопок. Зря полгода е№блись в своё время с выравниванием элементов...
