### ISSUE TITLE
Не изменяется порт при ручной настройке

### ISSUE THREAD

**Issue by pantryk** [pavel-pimenov/flylinkdc-r5xx#1721]
При настройке перенаправления портов вручную порт в поле "Torrent" не изменяется. При вводе значения отличного от изначального (я вводил 9007) и закрытия настроек кнопкой OK. Данная настройка записывается в файл DCPlusPlus.xml, однако клиент продолжает слушать 8999. При этом в момент закрытия программы файл настроек опять переписывается и там сохраняется дефултное значение 8999.  Порты в полях TCP и UDP при этом изменяются, сохраняются и слушаются адекватно. Проверено на двух разных машинах Win7 и одной Win10. Программа устанавливалась в каталог D:\Programs\FlylinkDC++\. Проверено на сборке 21131 х64, которая скачивается с сайта, и на сборке 21862, после автоматического обновления.

**Comment by Krulk** [comment]
Подтверждаю, не сохраняется Тореент порт. Только зачем этот порт изменять, да и зачем он вообще нужен непонятно, uTorrent скачивает/раздаёт и без него наверно в пассивном режиме?
