### ISSUE TITLE
Github и Firefox 52, или пора искать замену Github'у

### ISSUE THREAD

**Issue by JeanPaulLucien** [pavel-pimenov/flylinkdc-r5xx#1723]
Это сообщение не о Flylink. Однако, я считаю, что оно стоит внимания, так как затрудняет работу многих пользователей с Github. 
Последняя версия Firefox для XP - 52-ая, та же версия является последней ESR с XUL. За короткий период уже часть функционала Github'а не работает на 52 версии Firefox. А именно: просмотр языков репозитория, изменение файлов, переключение ветвей. Прежде эти возможности (в начале года) работали, но не работали на 42-ой версии. 
Этим я хочу сказать, что пользователи Firefox ущемляются Github'ом, и что нужно Github'у искать замену. Ибо это - пороховая бочка.

**Comment by JeanPaulLucien** [comment]
Ещё оказывается и сообщения редактировать не могу.

**Comment by DjArt** [comment]
Так, мне кажется, это ваш выбор - сидеть на XP. И срок её поддержки **создателями** давно истёк. Команда Firefox не имеет желания возится с портированием новых версий под неподдерживаемую ОС, как и команда разработчиков GitHub не желает иметь разные кодовые базы проекта(имею ввиду сам GitHub) под разные браузеры. То есть команды разработчиков не хотят тратить своё время на поддержку того, что не поддерживает даже сам создатель. А вы тут вселенский заговор какой-то описываете.
