### ISSUE TITLE
При скачивании торрентов скорость не отображается в панели состояния.

### ISSUE THREAD

**Issue by kotenok2000** [pavel-pimenov/flylinkdc-r5xx#1725]
скорость скачивания торрентов не учитывается.
![Снимок экрана (52)](https://user-images.githubusercontent.com/8822292/64080414-98451580-ccfc-11e9-9de8-0b1dfa71dec7.png)

**Comment by pavel-pimenov** [comment]
Да, есть такое в панеле состояния отображается скорость только от протокола DC++
