### ISSUE TITLE
Смена темы не меняет иконки панели инструментов

### ISSUE THREAD

**Issue by adem4ik** [pavel-pimenov/flylinkdc-r5xx#1729]
**Версия:** r504-x64 build 22038

1) Открыть настройки
2) Перейти в "Настройки интерфейса" - "Темы для FlylinkDC++"
3) Сменить тему, например на Tango
4) Перезапустить программу

**Результат:** тема иконок панели инструментов остаётся стандартной
![image](https://user-images.githubusercontent.com/4707112/68541439-da539d00-03b8-11ea-8e3e-4fb26a27aee8.png)
**Ожидаемый результат:** тема иконок панели инструментов сменяется (ниже скриншот из более старой версии)
![image](https://user-images.githubusercontent.com/4707112/68541448-053df100-03b9-11ea-8823-c9429881fc4f.png)

**Доп. информация:** проблема появилась после обновления до последней версии - r504-x64 build 22038. Попробовал более старые версии из https://cloud.mail.ru/public/9J3w/6A3wMMV2R, проблема воспроизводится в beta-build-22037 и beta-build-22039, в beta-build-22019 её уже нет.

Аналогичная проблема - тема иконок в дереве окна "Настройки" тоже должна меняться, но она не меняется.
![image](https://user-images.githubusercontent.com/4707112/68541516-e855ed80-03b9-11ea-9a18-c6a8113c1ec2.png)

**Comment by pavel-pimenov** [comment]
а до обновления тема менялась корректно?

**Comment by adem4ik** [comment]
да, до обновления стабильной версии на 22038 тема менялась.

**Comment by pavel-pimenov** [comment]
Спасибо. исправлено.
к вечеру будет обновление.

**Comment by adem4ik** [comment]
Благодарю, исправление подтверждаю.
