### ISSUE TITLE
При темах отличных от стандартной иконки типов файлов отображаются не корректно

### ISSUE THREAD

**Issue by adem4ik** [pavel-pimenov/flylinkdc-r5xx#1730]
**Версия:** r504-x64 build 22051

1) Открыть настройки
2) Перейти в "Настройки интерфейса" - "Темы для FlylinkDC++"
3) Сменить тему на любую кроме стандартной, например на Tango
4) Перезапустить программу
5) Открыть список файлов (например свой), либо запустить поиск файлов

**Результат:** 
![image](https://user-images.githubusercontent.com/4707112/68677807-28fa6600-0576-11ea-9efc-48ec2dc8af36.png)

**Ожидаемый результат:** 
![image](https://user-images.githubusercontent.com/4707112/68677960-6c54d480-0576-11ea-9aab-5b8a409e595b.png)

**Дополнительная информация:** 
Проблема появилась после исправления https://github.com/pavel-pimenov/flylinkdc-r5xx/issues/1729 т.е. в версии r504-x64-build-22044 . Предполагаю, что это как-то связано с тем, что теперь смена темы иконок также влияет и на иконки папок в списках файлов, и на иконки типов файлов в окне поиска.

Ранее (<= r504-x64-build-22021) они всегда брались из стандартной темы, вне зависимости от выбранной темы, выбор темы влиял только на отображение иконок на панели управления и в окне настроек. 

Ниже пример из r504-x64 build 22051 и r504-x64 build 22021 с выбранной темой Tango:
r504-x64 build 22051
![image](https://user-images.githubusercontent.com/4707112/68678253-0fa5e980-0577-11ea-99a8-ee3983de60ca.png)
r504-x64 build 22021
![image](https://user-images.githubusercontent.com/4707112/68678600-ac688700-0577-11ea-98bb-1650383aec99.png)

r504-x64 build 22051
![image](https://user-images.githubusercontent.com/4707112/68678310-2a785e00-0577-11ea-8495-890f0f4b48ed.png)
r504-x64 build 22021
![image](https://user-images.githubusercontent.com/4707112/68678719-e9347e00-0577-11ea-90c8-42c78c1e55d2.png)

**Comment by pavel-pimenov** [comment]
Нарисовать новые иконки для тем у меня возможности нет возможности.
верну функционал отображения в build 22021
иконки в нужных окнах будут забираться всегда из базового модуля.
ок?

**Comment by adem4ik** [comment]
думаю да, это будет лучше, чем спутанные иконки файлов/папок.

**Comment by pavel-pimenov** [comment]
@adem4ik обновил бетку - проверьте на каких диалогах есть косяки с вашей темой и скиньте скрины. я поправлю и вечером сделаю обновление релизной ветки.

**Comment by adem4ik** [comment]
@pavel-pimenov
Проверял в **FlylinkDC-r505-x64-beta-build-22069-2019.11.13-12.30.47.7z**:

1) Файл - Открыть собственный список файлов
![image](https://user-images.githubusercontent.com/4707112/68759203-ae3e5300-0628-11ea-92cb-a149b68df38f.png)

2) Открыть любой чужой список файлов
![image](https://user-images.githubusercontent.com/4707112/68759662-8d2a3200-0629-11ea-8128-7344d0e55a7e.png)

3) Открыть окно поиска, вбить любое поисковое слово, например "test"
![image](https://user-images.githubusercontent.com/4707112/68759446-21e06000-0629-11ea-9e54-4eaf67551d0a.png)

4) В окнах: Очередь скачивания, Завершённые скачивания, Очередь отдачи, Завершённые отдачи
![image](https://user-images.githubusercontent.com/4707112/68759974-37a25500-062a-11ea-9639-b0e5441af9eb.png)

**Comment by pavel-pimenov** [comment]
Обновил - проверьте.

**Comment by adem4ik** [comment]
Обновился до r504-x64 build 22075, проверил - проблема исправлена.
