### ISSUE TITLE
Повторный вход на ADC хаб ломает механизм идентификации

### ISSUE THREAD

**Issue by Tantrix** [pavel-pimenov/flylinkdc-r5xx#1733]
https://youtu.be/EjR1gjBfBD0

Подозреваю, что это связано с механизмом генерации нового никнейма для повторного подключения. Никнейм ладно, идентификатор-то нафига на лету менять? Естественно, ADC хабы начинают ругаться и выкидывать такой клиент, так как в отличие от NMDC хабов CID им необходим.

Конкретный адрес (с шифрованием или без) не имеет значения, та же самая ситуация возникает при редиректе на уже подключенный ADC хаб. Или нескольких редиректах.

**Comment by pavel-pimenov** [comment]
На связи? можешь сделать мне полигон чтобы повторить и поправить этот баг?

**Comment by HadesDCH** [comment]
Anytime testbed is here:
adcs://dc-united.ddns.net:9111
or adc:/dc-united.ddns.net:911


________________________________

**Comment by Tantrix** [comment]
> 
> 
> На связи? можешь сделать мне полигон чтобы повторить и поправить этот баг?

Привет!

Это несложно.

По сути, для этого нужно попробовать зайти дважды на один и тот же ADC хаб, чтобы сработал механизм генерации нового никнейма, а вместе с ним и нового CID. И ещё понадобится один или несколько других ADC хабов, дабы ошибка была наглядной, а то хаб тов. Hades намеренно разрешает одинаковые идентификаторы, что есть плохо.

Как воспроизвести:

1) Соединяешься с несколькими разными ADC хабами, любыми (лишь бы это был не хаб тов. Hades).
2) Добавляешь вручную адрес adcs://novosibirsk.dc-dev.club:7111 в Избранные, подключаешься.
3) Добавляешь в Избранные вручную адрес adc://dc-dev.club:711 но в настройках хаба выбираешь новый случайный никнейм, соединяешься с ним.

![Screenshot_1](https://user-images.githubusercontent.com/50278147/97096632-c1023a00-1677-11eb-98c7-731e17745885.png)

4) Переходишь на вкладку хаба с адресом adcs://novosibirsk.dc-dev.club:7111 и видишь сообщение, что в момент подключения к adc://dc-dev.club:711 был сгенерирован новый CID.
5) Ждёшь пару минут или вручную переподключаешься к любым другим ADC хабам. Они ругаются. Да и хаб тов. Hades тоже говорит, что, мол, обновления CID на лету запрещены.

![Screenshot_2](https://user-images.githubusercontent.com/50278147/97096634-c2336700-1677-11eb-935c-45a90b6d960d.png)

**Comment by HadesDCH** [comment]
Новосибирский хаб не проверяет pid / cid, что нарушает протокол adc. Это временный (небезопасный) патч, который необходимо удалить как можно скорее. Лучше протестировать на других концентраторах adc.

**Comment by Tantrix** [comment]
Bump!

**Comment by Tantrix** [comment]
Новое видео с иллюстрацией бага и простым его воспроизведением: https://youtu.be/1tS2HBuQtDM

**Comment by pavel-pimenov** [comment]
19:08:00] *** Connecting to adc://dc-dev.club:711 ...
[19:08:01] *** Connected
[19:08:01] <♜♜♜ Novosibirsk Forever ♜♜♜> This hub is running ADCH++ 3.0.0  Aramaic 3 [Feb.12.2022] [AMD EPYC 7763] ZorinOS Ultimate.
[19:08:01] <♜♜♜ Novosibirsk Forever ♜♜♜> You are hammering the hub  (0.48 times / min) with the Min Shared files limit , cool down ... , or you will be kicked !!!!
[19:08:01] <♜♜♜ Novosibirsk Forever ♜♜♜> You are redirected because: Your number of shared files ( 15 ) is too low, the minimum required number of files is 976543210
[19:08:01] *** You are redirected because: Your number of shared files ( 15 ) is too low, the minimum required number of files is 976543210

**Comment by HadesDCH** [comment]
This hub isn't the best place to test that issue. I removed few lines of code in source to let  flylink violate adc protocol and connect with pid/cid issue. That is all i can do to deal with it on my side.Please test it on some uhubs here for example:
adc://ufo.dc-dev.club:811
