### ISSUE TITLE
Установить приоритет наборов шифров хотя бы для TLS 1.3

### ISSUE THREAD

**Issue by Tantrix** [pavel-pimenov/flylinkdc-r5xx#1737]
Как здесь: https://github.com/airdcpp/airgit/blob/master/airdcpp/airdcpp/CryptoManager.cpp#L113-L138

**TLS_AES_128_GCM_SHA256** требует меньше ресурсов нежели дефолтный на данный момент **TLS_AES_256_GCM_SHA384** при приемлемом уровне стойкости.

**Comment by pavel-pimenov** [comment]
У флая еще есть ALPN

https://github.com/pavel-pimenov/flylinkdc-r5xx/blob/158881e55cb3495f0f534ecdb6e749d3f246c4b4/client/CryptoManager.cpp#L103-L106

там тоже нужно звать SSL_CTX_set_ciphersuites по идее?
ты сам проверял как работает после патча?

**Comment by Tantrix** [comment]
Смотря что за идея (: ALPN-то нету больше нигде в клиентах, насколько я знаю.

Ну а когда клиенты договорились о версии шифрования (будет использоваться максимальная доступная, понятно), они будут обмениваться шифрами согласно списку. Выше = приоритетней.

AirDC++по дефолту выбирает 128/256, но соглашается на 256/384. Все довольны.

**Comment by pavel-pimenov** [comment]
Ок. заберу тогда кусок от Air - бетку сделаю сегодня вечером.

**Comment by pavel-pimenov** [comment]
Сделал так чтобы в окне передаче показывался шифр при котором прошел SSL_Accept
![изображение](https://user-images.githubusercontent.com/920705/70161047-82186e00-16cc-11ea-9406-97eda9e2494d.png)
