### ISSUE TITLE
Если я ввожу текст в поле поиска и нажимаю кнопку поиск текст куда то пропадает

### ISSUE THREAD

**Issue by kotenok2000** [pavel-pimenov/flylinkdc-r5xx#1738]
[bandicam 2020-03-12 15-19-40-943.zip](https://github.com/pavel-pimenov/flylinkdc-r5xx/files/4324121/bandicam.2020-03-12.15-19-40-943.zip)

**Comment by adem4ik** [comment]
![image](https://user-images.githubusercontent.com/4707112/80311988-de9f3580-87f3-11ea-8b8f-9f1b0c828a83.png)
