### ISSUE TITLE
Перестал работать поиск по торрентам

### ISSUE THREAD

**Issue by Farmaleon90** [pavel-pimenov/flylinkdc-r5xx#1740]
В результатах поиска перестали отображаться торренты торрент-RSS  в r504-x64 build 22388 и в r600-x64 build 22434, по видимому, не только в моём случаи. В нижней панели пропал DHT. В настрйоках включен поиск по торрентам, выделенный IP, фаервол настроен, Windows 10 x64.

**Comment by pavel-pimenov** [comment]
Исправлено. проверьте.

**Comment by Farmaleon90** [comment]
> Исправлено. проверьте.

Всё работает. Спасибо!
