### ISSUE TITLE
Не качает драйвера Nvidia

### ISSUE THREAD

**Issue by Krulk** [pavel-pimenov/flylinkdc-r5xx#1747]
r600-beta-x64 build 22767
Не качает файлы драйверов Nvidia строка "465.89". Не важно много хабов открыто или 1, не качает. Порты открыты, монитор зелёный. Apex качает почти сразу. А FL "Скачивание начинается...", "Соединение закрыто", "Соединение... [Тайм-аут соединения]"

Не качает:
465.89-desktop-win10-64bit-international-whql.exe

Помечен градусником и не качает (хотя это не вирус):
465.89-desktop-win8-win7-64bit-international-whql.exe

**Comment by pavel-pimenov** [comment]
Киньте tth файла

**Comment by Krulk** [comment]
Это было на белом ip. Сейчас мне выдают серый ip, проверить скачку толком не могу. Практически все файлы драйверов Nvidia помечены градусником и не качаются. Возможно дело было в этом.
Например строка "472.12". KZNEKZAYBPV3NQKQLHHQSKINVF4Z4JF3YTFRH4I

**Comment by pavel-pimenov** [comment]
![изображение](https://user-images.githubusercontent.com/920705/144747520-5367986f-bb03-4954-8294-0379491fc487.png)

**Comment by Krulk** [comment]
У меня качает у того же юзера, на той же скорости, несмотря на порядка 40 источников. На всех килентах одинаково. В общем всё в порядке. Можно закрывать.
