### ISSUE TITLE
Исключить тип mp4 из фильтра поиска Аудио

### ISSUE THREAD

**Issue by Krulk** [pavel-pimenov/flylinkdc-r5xx#18]
Тип mp4 надо исключить из фильтра Аудио при поиске, он уже есть в фильтре Видео где ему и место. Иначе ищешь с фильтром Аудио музыку, а выдаёт mp4 видео файлы.
К фильтру аудио добавить форматы *.wv и *.m4a если их там нет.

**Comment by pavel-pimenov** [comment]
Привет.
mp4 включен в блок видео но возвращается другими клиентами
https://yadi.sk/i/VcJoeYTfiAiFP
полный список у флайлинка зашит в клиент тут
https://github.com/pavel-pimenov/flylinkdc-r5xx/blob/d2878d5e27909a1680ab8d5e093fdba36025ca55/client/ShareManager.cpp#L1882

во флае он немного расширенный и исправлен
при этом в StrongDC++ 2.42 
mp4 находится почему-то в группе Audio.


static const char* typeAudio[] = { ".mp3", ".mp2", ".mid", ".wav", ".ogg", ".wma", ".669", ".aac", ".aif", ".amf", ".ams", ".ape", ".dbm", ".dmf", ".dsm", ".far", ".mdl", ".med", ".mod", ".mol", ".mp1", ".mp4", ".mpa", ".mpc", ".mpp", ".mtm", ".nst", ".okt", ".psm", ".ptm", ".rmi", ".s3m", ".stm", ".ult", ".umx", ".wow" };
static const char* typeCompressed[] = { ".zip", ".ace", ".rar", ".arj", ".hqx", ".lha", ".sea", ".tar", ".tgz", ".uc2" };
static const char* typeDocument[] = { ".htm", ".doc", ".txt", ".nfo", ".pdf", ".chm" };
static const char* typeExecutable[] = { ".exe", ".com" };
static const char* typePicture[] = { ".jpg", ".gif", ".png", ".eps", ".img", ".pct", ".psp", ".pic", ".tif", ".rle", ".bmp", ".pcx", ".jpe", ".dcx", ".emf", ".ico", ".psd", ".tga", ".wmf", ".xif" };
static const char* typeVideo[] = { ".mpg", ".mov", ".asf", ".avi", ".pxp", ".wmv", ".ogm", ".mkv", ".m1v", ".m2v", ".mpe", ".mps", ".mpv", ".ram", ".vob" };

static const string type2Audio[] = { ".au", ".it", ".ra", ".xm", ".aiff", ".flac", ".midi", };
static const string type2Compressed[] = { ".gz" };
static const string type2Picture[] = { ".ai", ".ps", ".pict", ".jpeg", ".tiff" };
static const string type2Video[] = { ".rm", ".divx", ".mpeg", ".mp1v", ".mp2v", ".mpv1", ".mpv2", ".qt", ".rv", ".vivo" };


я поправлю результаты поиска локально и отфильтрую лишнее в клиенте - ожидайте новой бетки

**Comment by pavel-pimenov** [comment]
m4a у флая уже есть в звуке - а вот что такое .mv я не знаю -у меня и не ищется такое расширение.

**Comment by Krulk** [comment]
Если .mp4 находится только в аудио, тогда почему когда ищешь видео такие файлы тоже находятся?
.wv это WavPack https://ru.wikipedia.org/wiki/WavPack

**Comment by pavel-pimenov** [comment]
mp4 для видео возвращают клиенты флайлинк, тогда как клиенты типа StrongDC++ вертают mp4 когда клиент просит звук. (тут уже ничего не поделаешь т.к. таблицы соответствия зашиты в клиентах жестко и различаются а код типа файла передается в команде запроса всем клиентам одинаково)
но я это поправлю сегодня вечером и все типы будут дополнительно на клиенте фильтроваться в соответствии с выбором.
результат будет уже лучше:
https://yadi.sk/i/qv3KmpMyiAt58
двойное расширение mp4.mp3 это что за хрень не знаешь случайно?

.wv тоже добавлю к звукам - хотя я на своих хабах не нашел таких файлов вообще...

p.s.
мне уже писали про подобную ошибку

>> Обнаружил следующий баг в флае (и стабильной и в бете):
>> Ввожу в поиск Windows 10
>> ставлю тип файла CD-DVD Image
>> а он всеравно мне выдает всякие ini файлы и прочий мусор

я ее поправил а вот про другие типы что-то забыл.
сделал общий алгоритм - и все будет ок.

			const Search::TypeModes l_local_filter[] =
			{
				Search::TYPE_AUDIO,
				Search::TYPE_COMPRESSED,
				Search::TYPE_DOCUMENT,
				Search::TYPE_EXECUTABLE,
				Search::TYPE_PICTURE,
				Search::TYPE_VIDEO,
				Search::TYPE_CD_IMAGE
			};
			for (auto k = 0; k < _countof(l_local_filter); ++k)
			{
				if (m_search_param.m_file_type == l_local_filter[k])
				{
					const bool l_is_filter = ShareManager::checkType(l_ext, l_local_filter[k]);
					if (!l_is_filter)
					{
						m_droppedResults++;
						return;
					}
				}
			}

**Comment by Krulk** [comment]
Двойное расширение, видимо кто-то неправильно именует файлы.
Файлов .wv находится очень много, если искать с фильтром "Любой".

**Comment by pavel-pimenov** [comment]
А точно - опечатка. а mediainfo по  .wv что-то выдает?
а то у меня не добавлено это расширение к сканированию.

**Comment by pavel-pimenov** [comment]
D:\tools\MediaInfo_CLI_0.7.75>MediaInfo.exe 1.wv
General
Complete name                            : 1.wv
Format                                   : WavPack
File size                                : 4.64 MiB
Duration                                 : 1mn 0s
Overall bit rate mode                    : Variable
Overall bit rate                         : 639 Kbps
Album                                    : Христос воскресе
Track name                               : 'Плотию уснув', сербский напев
Track name/Position                      : 06
Performer                                : Дивна Любоевич и 'Мелоди'
Genre                                    : A Cappella
Recorded date                            : 2007
Comment                                  : Exact Audio Copy

Audio
Format                                   : WavPack
Format profile                           : 4.07
Duration                                 : 1mn 0s
Bit rate mode                            : Variable
Bit rate                                 : 639 Kbps
Channel(s)                               : 2 channels
Sampling rate                            : 44.1 KHz
Bit depth                                : 16 bits
Compression ratio                        : 2.210
Stream size                              : 4.64 MiB (100%)
Encoding settings                        : -h -m

**Comment by pavel-pimenov** [comment]
Авто-обновитесь до последней бетке. все стало ок?

**Comment by Krulk** [comment]
С .mp4 всё стало нормально.
А .wv в результатах поиска Аудио не выдаёт.

**Comment by pavel-pimenov** [comment]
.wv добавлен верно
static const string type2Audio[] = { ".au", ".it", ".ra", ".xm", ".aiff", ".flac", ".midi", ".wv"};
начнет выдаваться со временем когда юзера обновят клиента и перехешируют им эти файлы.
возможно конечно запустить принудительное обновление типа этих файлов но я пока это не буду делать.

**Comment by pavel-pimenov** [comment]
Хотя нет - поправлю я вспомнил как я лечил ошибку с типом mp4 и автоматом переводил его на видео в версии r365
в след бетке починю и тип wv аналогично.
		if (l_rev < 365)
		{
			m_flySQLiteDB.executenonquery("update fly_file set ftype=6 where name like '%.mp4' or name like '%.fly'");
		}

**Comment by pavel-pimenov** [comment]
добавил конвертацию.
