### ISSUE TITLE
Глючное поле в фаворитах OP Chat Names

### ISSUE THREAD

**Issue by pavel-pimenov** [pavel-pimenov/flylinkdc-r5xx#19]
В фаворитах поле OP Chat Names, когда имеет что либо, через разделитель ; должно открывать лички от этого ника при входе на хаб
но поле абсолютно ничего не делает.

![op-names](https://cloud.githubusercontent.com/assets/920705/9006448/ea38e008-378f-11e5-820a-2ee5272cadfd.png)

**Comment by SCALOlaz** [comment]
![2015-07-31 15-22-14](https://cloud.githubusercontent.com/assets/417049/9006449/4e20579c-3798-11e5-9440-40224c349419.png)
Если "взлетит" и появится реальная необходимость в этом поле, можно подправить текст или добавить подсказку
