### ISSUE TITLE
Из Очереди скачки и Очереди отдачи исчезла колонка Тип

### ISSUE THREAD

**Issue by Krulk** [pavel-pimenov/flylinkdc-r5xx#21]
Из Очереди скачки и Очереди отдачи исчезла колонка для сортировки по Типу файла, или её там и не было. В Strong и Apex её тоже нет, а в GL есть. Хотело бы увидеть её и в FL.

**Comment by pavel-pimenov** [comment]
Я не удалял - думаю что не было.
добавлю завтра

**Comment by pavel-pimenov** [comment]
Добавил - ожидайте вечером в бетке
