### ISSUE TITLE
Двоение ников в списке юзеров

### ISSUE THREAD

**Issue by Krulk** [pavel-pimenov/flylinkdc-r5xx#22]
Опять наблюдается двоение ников. Включил комп, запустился FL и показал такое, Win10x64:
http://f6.s.qip.ru/C38ZWvSR.png

**Comment by pavel-pimenov** [comment]
Подтверждается - где-то сломал.
повторяется если после коннекта нажать F5
найду и поправлю

**Comment by pavel-pimenov** [comment]
Сегодня вечером проверьте бетку и отпишите как стало в ней.

**Comment by pavel-pimenov** [comment]
Поправил
