### ISSUE TITLE
Странно работает список поисковых запросов

### ISSUE THREAD

**Issue by Krulk** [pavel-pimenov/flylinkdc-r5xx#25]
Когда ищешь, поисковые запросы сохраняются в выпадающем меню. Сейчас оно работает неправильно (Как до конца не понял):
1. Поисковые запросы сохраняется в нём сверху, но если закрыть окно а потом открыть его, последние запросы каждый раз оказываются в конце списка.
2. Старые поисковые запросы пока список растёт перемещаются вверх и вообще не вытесняются когда список полон, если в 1 окне поиска не начать искать 10 раз. 
3. Список сортируется рандомно.

 По идее оно должно работать так:
1. Новое слово добавлять вверх, список растёт, удаляется самое нижнее слово, если список полон.
2. Если слово уже есть в списке, переместить его вверх.
3. Список запросов сохраняется после каждого поиска, чтобы если открыть новое окно поиска или закрыть старое и открыть новое, список был всегда актуальным.

**Comment by pavel-pimenov** [comment]
Принятно - думаю там сортировка стоит по алфавиту.
и при открытии комбик все записи сам тасует

**Comment by pavel-pimenov** [comment]
Исправлено - ожидай след бетку

**Comment by Krulk** [comment]
Не исправлено. Чтобы повторить, нужно очистить поиск, искать последовательно: 01, 02, 03, 04, 05, 06, 07, 08, 09, 10. Закрыть поиск. Открыть поиск и увидеть, что запросы в списке перепутаны: http://f5.s.qip.ru/GjeazMDL.png
03 постоянно перескакивает во 2 строчку. Это пример на цифрах, с буквами вроде ещё более непредсказуемо.
